export * from '../reponse-dto/user.res.dto';
export * from '../reponse-dto/auth.res.dto';
export * from './department.dto';
export * from './subject.dto';
export * from './semester.dto';
export * from './teacher.dto';
export * from './revendication.dto';
export * from './transcript.dto';
export * from './grade.dto';
