--
-- PostgreSQL database dump
--

-- Dumped from database version 17.2
-- Dumped by pg_dump version 17.2

-- Started on 2025-08-22 17:20:46

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET transaction_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- TOC entry 218 (class 1259 OID 108465)
-- Name: departments; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.departments (
    id bigint NOT NULL,
    name character varying(100) NOT NULL
);


ALTER TABLE public.departments OWNER TO postgres;

--
-- TOC entry 217 (class 1259 OID 108464)
-- Name: departments_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.departments ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.departments_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 239 (class 1259 OID 108603)
-- Name: grade_claim; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.grade_claim (
    id bigint NOT NULL,
    creation_date timestamp(6) with time zone NOT NULL,
    last_modified_date timestamp(6) with time zone,
    cause character varying(255),
    description character varying(1000),
    period_label character varying(255),
    requested_score double precision,
    resolved_at timestamp(6) without time zone,
    status character varying(255),
    teacher_comment character varying(1000),
    id_grade bigint,
    id_semester bigint,
    id_student bigint,
    CONSTRAINT grade_claim_status_check CHECK (((status)::text = ANY ((ARRAY['PENDING'::character varying, 'APPROVED'::character varying, 'REJECTED'::character varying])::text[])))
);


ALTER TABLE public.grade_claim OWNER TO postgres;

--
-- TOC entry 240 (class 1259 OID 108611)
-- Name: grade_claim_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

CREATE SEQUENCE public.grade_claim_seq
    START WITH 1
    INCREMENT BY 50
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER SEQUENCE public.grade_claim_seq OWNER TO postgres;

--
-- TOC entry 242 (class 1259 OID 116657)
-- Name: grade_claims; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.grade_claims (
    id bigint NOT NULL,
    created_at timestamp(6) without time zone,
    rejection_reason character varying(255),
    resolved_at timestamp(6) without time zone,
    status character varying(255),
    cause text,
    description text,
    period_label character varying(255),
    requested_score double precision NOT NULL,
    teacher_comment text,
    created_by_id bigint,
    grade_id bigint NOT NULL,
    semester_id bigint,
    student_id bigint NOT NULL,
    CONSTRAINT grade_claims_status_check CHECK (((status)::text = ANY ((ARRAY['PENDING'::character varying, 'APPROVED'::character varying, 'REJECTED'::character varying])::text[])))
);


ALTER TABLE public.grade_claims OWNER TO postgres;

--
-- TOC entry 241 (class 1259 OID 116656)
-- Name: grade_claims_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

CREATE SEQUENCE public.grade_claims_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER SEQUENCE public.grade_claims_id_seq OWNER TO postgres;

--
-- TOC entry 4937 (class 0 OID 0)
-- Dependencies: 241
-- Name: grade_claims_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: postgres
--

ALTER SEQUENCE public.grade_claims_id_seq OWNED BY public.grade_claims.id;


--
-- TOC entry 219 (class 1259 OID 108470)
-- Name: grade_report; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.grade_report (
    id bigint NOT NULL,
    creation_date timestamp(6) with time zone NOT NULL,
    last_modified_date timestamp(6) with time zone,
    gpa double precision,
    id_semesters bigint,
    id_students bigint,
    pdf_path character varying(255),
    status character varying(255)
);


ALTER TABLE public.grade_report OWNER TO postgres;

--
-- TOC entry 230 (class 1259 OID 108553)
-- Name: grade_report_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

CREATE SEQUENCE public.grade_report_seq
    START WITH 1
    INCREMENT BY 50
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER SEQUENCE public.grade_report_seq OWNER TO postgres;

--
-- TOC entry 220 (class 1259 OID 108477)
-- Name: grades; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.grades (
    id bigint NOT NULL,
    creation_date timestamp(6) with time zone NOT NULL,
    last_modified_date timestamp(6) with time zone,
    comments character varying(255),
    period_label character varying(255),
    grade_type character varying(255),
    value double precision,
    id_users bigint,
    id_semester bigint,
    id_students bigint,
    id_subject bigint,
    max_value double precision,
    CONSTRAINT grades_grade_type_check CHECK (((grade_type)::text = ANY ((ARRAY['ASSIGNMENT'::character varying, 'EXAM'::character varying, 'QUIZ'::character varying, 'PROJECT'::character varying])::text[])))
);


ALTER TABLE public.grades OWNER TO postgres;

--
-- TOC entry 231 (class 1259 OID 108554)
-- Name: grades_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

CREATE SEQUENCE public.grades_seq
    START WITH 1
    INCREMENT BY 50
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER SEQUENCE public.grades_seq OWNER TO postgres;

--
-- TOC entry 221 (class 1259 OID 108485)
-- Name: grading_window; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.grading_window (
    id bigint NOT NULL,
    creation_date timestamp(6) with time zone NOT NULL,
    last_modified_date timestamp(6) with time zone,
    active boolean,
    end_date date,
    name character varying(255),
    start_date date,
    id_semester bigint
);


ALTER TABLE public.grading_window OWNER TO postgres;

--
-- TOC entry 232 (class 1259 OID 108555)
-- Name: grading_window_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

CREATE SEQUENCE public.grading_window_seq
    START WITH 1
    INCREMENT BY 50
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER SEQUENCE public.grading_window_seq OWNER TO postgres;

--
-- TOC entry 223 (class 1259 OID 108491)
-- Name: invite_token; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.invite_token (
    id bigint NOT NULL,
    claimed boolean NOT NULL,
    expires_at timestamp(6) with time zone NOT NULL,
    role character varying(255) NOT NULL,
    token character varying(255) NOT NULL,
    CONSTRAINT invite_token_role_check CHECK (((role)::text = ANY ((ARRAY['ADMIN'::character varying, 'STUDENT'::character varying, 'TEACHER'::character varying])::text[])))
);


ALTER TABLE public.invite_token OWNER TO postgres;

--
-- TOC entry 222 (class 1259 OID 108490)
-- Name: invite_token_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.invite_token ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.invite_token_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 224 (class 1259 OID 108499)
-- Name: report_record; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.report_record (
    id bigint NOT NULL,
    creation_date timestamp(6) with time zone NOT NULL,
    last_modified_date timestamp(6) with time zone,
    academic_year character varying(255),
    class_id bigint,
    download_url character varying(255),
    faculty character varying(255),
    generated_by bigint,
    gpa double precision,
    pdf_path character varying(255),
    report_type character varying(50),
    semester_id bigint,
    status character varying(255),
    student_id bigint,
    subject_id bigint,
    university_name character varying(255)
);


ALTER TABLE public.report_record OWNER TO postgres;

--
-- TOC entry 233 (class 1259 OID 108556)
-- Name: report_record_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

CREATE SEQUENCE public.report_record_seq
    START WITH 1
    INCREMENT BY 50
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER SEQUENCE public.report_record_seq OWNER TO postgres;

--
-- TOC entry 225 (class 1259 OID 108506)
-- Name: semesters; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.semesters (
    id bigint NOT NULL,
    creation_date timestamp(6) with time zone NOT NULL,
    last_modified_date timestamp(6) with time zone,
    active boolean,
    end_date date,
    name character varying(255),
    order_index integer,
    start_date date
);


ALTER TABLE public.semesters OWNER TO postgres;

--
-- TOC entry 234 (class 1259 OID 108557)
-- Name: semesters_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

CREATE SEQUENCE public.semesters_seq
    START WITH 1
    INCREMENT BY 50
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER SEQUENCE public.semesters_seq OWNER TO postgres;

--
-- TOC entry 226 (class 1259 OID 108511)
-- Name: student_info_requests; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.student_info_requests (
    id bigint NOT NULL,
    creation_date timestamp(6) with time zone NOT NULL,
    last_modified_date timestamp(6) with time zone,
    created_at timestamp(6) without time zone,
    rejection_reason character varying(255),
    requested_changes_json text NOT NULL,
    status character varying(255),
    student_id bigint NOT NULL,
    CONSTRAINT student_info_requests_status_check CHECK (((status)::text = ANY ((ARRAY['PENDING'::character varying, 'APPROVED'::character varying, 'REJECTED'::character varying])::text[])))
);


ALTER TABLE public.student_info_requests OWNER TO postgres;

--
-- TOC entry 235 (class 1259 OID 108558)
-- Name: student_info_requests_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

CREATE SEQUENCE public.student_info_requests_seq
    START WITH 1
    INCREMENT BY 50
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER SEQUENCE public.student_info_requests_seq OWNER TO postgres;

--
-- TOC entry 227 (class 1259 OID 108519)
-- Name: students; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.students (
    id bigint NOT NULL,
    creation_date timestamp(6) with time zone NOT NULL,
    last_modified_date timestamp(6) with time zone,
    cycle character varying(255),
    date_of_birth date,
    email character varying(255),
    first_name character varying(255),
    last_name character varying(255),
    level character varying(255),
    matricule character varying(255),
    place_of_birth character varying(255),
    speciality character varying(255),
    CONSTRAINT students_cycle_check CHECK (((cycle)::text = ANY ((ARRAY['BACHELOR'::character varying, 'MASTER'::character varying, 'PHD'::character varying])::text[]))),
    CONSTRAINT students_level_check CHECK (((level)::text = ANY ((ARRAY['LEVEL1'::character varying, 'LEVEL2'::character varying, 'LEVEL3'::character varying, 'LEVEL4'::character varying, 'LEVEL5'::character varying])::text[])))
);


ALTER TABLE public.students OWNER TO postgres;

--
-- TOC entry 236 (class 1259 OID 108559)
-- Name: students_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

CREATE SEQUENCE public.students_seq
    START WITH 1
    INCREMENT BY 50
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER SEQUENCE public.students_seq OWNER TO postgres;

--
-- TOC entry 228 (class 1259 OID 108528)
-- Name: subject; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.subject (
    id bigint NOT NULL,
    creation_date timestamp(6) with time zone NOT NULL,
    last_modified_date timestamp(6) with time zone,
    active boolean,
    code character varying(255),
    credits numeric(38,2),
    cycle character varying(255),
    description character varying(500),
    id_teacher bigint,
    level character varying(255),
    name character varying(255),
    department_id bigint,
    id_semester bigint,
    CONSTRAINT subject_cycle_check CHECK (((cycle)::text = ANY ((ARRAY['BACHELOR'::character varying, 'MASTER'::character varying, 'PHD'::character varying])::text[]))),
    CONSTRAINT subject_level_check CHECK (((level)::text = ANY ((ARRAY['LEVEL1'::character varying, 'LEVEL2'::character varying, 'LEVEL3'::character varying, 'LEVEL4'::character varying, 'LEVEL5'::character varying])::text[])))
);


ALTER TABLE public.subject OWNER TO postgres;

--
-- TOC entry 237 (class 1259 OID 108560)
-- Name: subject_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

CREATE SEQUENCE public.subject_seq
    START WITH 1
    INCREMENT BY 50
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER SEQUENCE public.subject_seq OWNER TO postgres;

--
-- TOC entry 229 (class 1259 OID 108537)
-- Name: users; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.users (
    id bigint NOT NULL,
    creation_date timestamp(6) with time zone NOT NULL,
    last_modified_date timestamp(6) with time zone,
    active boolean,
    department character varying(100),
    email character varying(255),
    first_name character varying(255),
    last_name character varying(255),
    must_change_password boolean,
    password character varying(255),
    phone character varying(30),
    role character varying(255),
    username character varying(255),
    CONSTRAINT users_role_check CHECK (((role)::text = ANY ((ARRAY['ADMIN'::character varying, 'STUDENT'::character varying, 'TEACHER'::character varying])::text[])))
);


ALTER TABLE public.users OWNER TO postgres;

--
-- TOC entry 238 (class 1259 OID 108561)
-- Name: users_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

CREATE SEQUENCE public.users_seq
    START WITH 1
    INCREMENT BY 50
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER SEQUENCE public.users_seq OWNER TO postgres;

--
-- TOC entry 4701 (class 2604 OID 116660)
-- Name: grade_claims id; Type: DEFAULT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.grade_claims ALTER COLUMN id SET DEFAULT nextval('public.grade_claims_id_seq'::regclass);


--
-- TOC entry 4907 (class 0 OID 108465)
-- Dependencies: 218
-- Data for Name: departments; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.departments (id, name) FROM stdin;
1	Mathematics Department
2	Physics Department
3	Chemistry Department
4	Biology Department
5	History Department
6	Philosophy & Critical Thinking Department
\.


--
-- TOC entry 4928 (class 0 OID 108603)
-- Dependencies: 239
-- Data for Name: grade_claim; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.grade_claim (id, creation_date, last_modified_date, cause, description, period_label, requested_score, resolved_at, status, teacher_comment, id_grade, id_semester, id_student) FROM stdin;
\.


--
-- TOC entry 4931 (class 0 OID 116657)
-- Dependencies: 242
-- Data for Name: grade_claims; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.grade_claims (id, created_at, rejection_reason, resolved_at, status, cause, description, period_label, requested_score, teacher_comment, created_by_id, grade_id, semester_id, student_id) FROM stdin;
\.


--
-- TOC entry 4908 (class 0 OID 108470)
-- Dependencies: 219
-- Data for Name: grade_report; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.grade_report (id, creation_date, last_modified_date, gpa, id_semesters, id_students, pdf_path, status) FROM stdin;
\.


--
-- TOC entry 4909 (class 0 OID 108477)
-- Dependencies: 220
-- Data for Name: grades; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.grades (id, creation_date, last_modified_date, comments, period_label, grade_type, value, id_users, id_semester, id_students, id_subject, max_value) FROM stdin;
2	2025-08-22 14:09:02.267144+00	\N	Excellent performance with strong understanding of the concepts	Midterm Assessment	EXAM	18	53	1	6	1	20
\.


--
-- TOC entry 4910 (class 0 OID 108485)
-- Dependencies: 221
-- Data for Name: grading_window; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.grading_window (id, creation_date, last_modified_date, active, end_date, name, start_date, id_semester) FROM stdin;
\.


--
-- TOC entry 4912 (class 0 OID 108491)
-- Dependencies: 223
-- Data for Name: invite_token; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.invite_token (id, claimed, expires_at, role, token) FROM stdin;
\.


--
-- TOC entry 4913 (class 0 OID 108499)
-- Dependencies: 224
-- Data for Name: report_record; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.report_record (id, creation_date, last_modified_date, academic_year, class_id, download_url, faculty, generated_by, gpa, pdf_path, report_type, semester_id, status, student_id, subject_id, university_name) FROM stdin;
\.


--
-- TOC entry 4914 (class 0 OID 108506)
-- Dependencies: 225
-- Data for Name: semesters; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.semesters (id, creation_date, last_modified_date, active, end_date, name, order_index, start_date) FROM stdin;
2	2025-08-22 08:09:19.750635+00	\N	t	2026-06-30	SEMESTER2	\N	2026-02-01
1	2025-08-22 08:06:37.807133+00	\N	f	2026-01-15	SEMESTER1	\N	2025-09-01
\.


--
-- TOC entry 4915 (class 0 OID 108511)
-- Dependencies: 226
-- Data for Name: student_info_requests; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.student_info_requests (id, creation_date, last_modified_date, created_at, rejection_reason, requested_changes_json, status, student_id) FROM stdin;
\.


--
-- TOC entry 4916 (class 0 OID 108519)
-- Dependencies: 227
-- Data for Name: students; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.students (id, creation_date, last_modified_date, cycle, date_of_birth, email, first_name, last_name, level, matricule, place_of_birth, speciality) FROM stdin;
1	2025-08-20 15:18:21.931844+00	\N	BACHELOR	\N	student1@example.com	Student1	Level1	LEVEL1	MAT2FEC32	\N	\N
2	2025-08-20 15:18:22.062072+00	\N	BACHELOR	\N	student2@example.com	Student2	Level2	LEVEL2	MAT594D6E	\N	\N
3	2025-08-20 15:18:22.204248+00	\N	BACHELOR	\N	student3@example.com	Student3	Level3	LEVEL3	MAT185D1B	\N	\N
4	2025-08-20 15:18:22.338021+00	\N	MASTER	\N	student4@example.com	Student4	Level4	LEVEL4	MATB185C8	\N	\N
5	2025-08-20 15:18:22.512794+00	\N	MASTER	\N	student5@example.com	Student5	Level5	LEVEL5	MAT9298BF	\N	\N
6	2025-08-20 15:18:22.627085+00	\N	BACHELOR	2000-01-01	student@example.com	Default	Student	LEVEL1	MAT6F632C	TestCity	Computer Science
52	2025-08-22 10:20:58.790054+00	\N	BACHELOR	\N	rita.banjo@student.university.com	Rita	Banjo	LEVEL1	MAT2025-101	\N	\N
53	2025-08-22 10:21:42.266067+00	\N	BACHELOR	\N	victor.okoye@student.university.com	Victor	Okoye	LEVEL1	MAT2025-102	\N	\N
54	2025-08-22 10:22:12.036399+00	\N	BACHELOR	\N	sophie.mbaye@student.university.com	Sophie	Mbaye	LEVEL1	MAT2025-103	\N	\N
55	2025-08-22 10:22:44.663603+00	\N	BACHELOR	\N	amina.koulibaly@student.university.com	Amina	Koulibaly	LEVEL1	MAT2025-104	\N	\N
56	2025-08-22 10:23:20.435955+00	\N	BACHELOR	\N	junior.mbanda@student.university.com	Junior	Mbanda	LEVEL1	MAT2025-105	\N	\N
57	2025-08-22 10:23:46.165982+00	\N	BACHELOR	\N	charlotte.nzinga@student.university.com	Charlotte	Nzinga	LEVEL1	MAT2025-106	\N	\N
60	2025-08-22 11:09:31.929016+00	\N	BACHELOR	\N	julia.omoh@student.university.com	Julia	Omoh	LEVEL2	MAT2025-201	\N	\N
61	2025-08-22 11:12:28.961538+00	\N	BACHELOR	\N	thierry.badu@student.university.com	Thierry	Badu	LEVEL2	MAT2025-202	\N	\N
62	2025-08-22 11:13:01.322013+00	\N	BACHELOR	\N	amina.gaye@student.university.com	Amina	Gaye	LEVEL2	MAT2025-203	\N	\N
63	2025-08-22 11:14:14.704542+00	\N	BACHELOR	\N	kofi.kamara@student.university.com	Kofi	Kamara	LEVEL2	MAT2025-204	\N	\N
64	2025-08-22 11:14:47.268257+00	\N	BACHELOR	\N	mari.sylla@student.university.com	Mari	Sylla	LEVEL2	MAT2025-205	\N	\N
65	2025-08-22 11:15:40.214745+00	\N	BACHELOR	\N	charlotte.kone@student.university.com	Charlotte	Kone	LEVEL2	MAT2025-206	\N	\N
66	2025-08-22 11:23:48.657063+00	\N	BACHELOR	\N	amina.wade@student.university.com	Amina	Wade	LEVEL3	MAT2025-301	\N	\N
67	2025-08-22 11:24:22.488459+00	\N	BACHELOR	\N	thierry.kabira@student.university.com	Thierry	Kabira	LEVEL3	MAT2025-302	\N	\N
68	2025-08-22 11:24:50.27401+00	\N	BACHELOR	\N	bola.funmi@student.university.com	Bola	Funmi	LEVEL3	MAT2025-303	\N	\N
69	2025-08-22 11:25:13.574237+00	\N	BACHELOR	\N	mario.kouame@student.university.com	Mario	Kouame	LEVEL3	MAT2025-304	\N	\N
70	2025-08-22 11:25:52.798738+00	\N	BACHELOR	\N	nora.simbe@student.university.com	Nora	Simbe	LEVEL3	MAT2025-305	\N	\N
71	2025-08-22 11:26:15.084217+00	\N	BACHELOR	\N	charlotte.kouadio@student.university.com	Charlotte	Kouadio	LEVEL3	MAT2025-306	\N	\N
\.


--
-- TOC entry 4917 (class 0 OID 108528)
-- Dependencies: 228
-- Data for Name: subject; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.subject (id, creation_date, last_modified_date, active, code, credits, cycle, description, id_teacher, level, name, department_id, id_semester) FROM stdin;
1	2025-08-22 12:42:28.581364+00	\N	t	MATH101	4.00	BACHELOR	Introduction to basic concepts in algebra, calculus, and geometry for LEVEL1 students.	\N	LEVEL1	Mathematics	1	1
2	2025-08-22 12:51:18.07358+00	\N	t	MATH201	4.00	BACHELOR	Introduction to basic concepts in algebra, calculus, and geometry for LEVEL1 students.	\N	LEVEL2	Mathematics	1	1
3	2025-08-22 12:54:15.10828+00	\N	t	MATH301	4.00	BACHELOR	Introduction to basic concepts in algebra, calculus, and geometry for LEVEL3 students.	\N	LEVEL3	Mathematics	1	1
4	2025-08-22 12:57:46.023336+00	\N	t	PHY101	3.00	BACHELOR	Fundamental concepts of mechanics, thermodynamics, and electromagnetism for LEVEL1 students.	\N	LEVEL1	Physics	2	1
5	2025-08-22 12:58:33.626088+00	\N	t	PHY201	3.00	BACHELOR	Fundamental concepts of mechanics, thermodynamics, and electromagnetism for LEVEL1 students.	\N	LEVEL2	Physics	2	1
6	2025-08-22 12:59:28.942748+00	\N	t	PHY301	3.00	BACHELOR	Fundamental concepts of mechanics, thermodynamics, and electromagnetism for LEVEL1 students.	\N	LEVEL3	Physics	2	1
7	2025-08-22 13:03:25.2085+00	\N	t	CHM101	3.00	BACHELOR	Introduction to general chemistry concepts including atomic structure, chemical bonding, stoichiometry, and states of matter.	\N	LEVEL1	Chemistry	3	1
8	2025-08-22 13:03:58.305106+00	\N	t	CHM201	3.00	BACHELOR	Introduction to general chemistry concepts including atomic structure, chemical bonding, stoichiometry, and states of matter.	\N	LEVEL2	Chemistry	3	1
9	2025-08-22 13:05:12.871849+00	\N	t	CHM301	3.00	BACHELOR	Introduction to general chemistry concepts including atomic structure, chemical bonding, stoichiometry, and states of matter.	\N	LEVEL3	Chemistry	3	1
10	2025-08-22 13:06:47.052994+00	\N	t	BIO101	5.00	BACHELOR	Introduction to biology covering cell structure, genetics, evolution, and basic ecology principles.	\N	LEVEL1	Biology	4	1
11	2025-08-22 13:07:21.456204+00	\N	t	BIO201	5.00	BACHELOR	Introduction to biology covering cell structure, genetics, evolution, and basic ecology principles.	\N	LEVEL2	Biology	4	1
12	2025-08-22 13:07:56.998325+00	\N	t	BIO301	5.00	BACHELOR	Introduction to biology covering cell structure, genetics, evolution, and basic ecology principles.	\N	LEVEL3	Biology	4	1
13	2025-08-22 13:09:45.820041+00	\N	t	HIS101	3.00	BACHELOR	Introduction to world history with a focus on ancient civilizations, medieval societies, and the foundations of modern nations.	\N	LEVEL1	History	5	1
14	2025-08-22 13:10:23.149685+00	\N	t	HIS201	3.00	BACHELOR	Introduction to world history with a focus on ancient civilizations, medieval societies, and the foundations of modern nations.	\N	LEVEL2	History	5	1
15	2025-08-22 13:11:05.951582+00	\N	t	HIS301	3.00	BACHELOR	Introduction to world history with a focus on ancient civilizations, medieval societies, and the foundations of modern nations.	\N	LEVEL3	History	5	1
16	2025-08-22 13:13:19.909525+00	\N	t	CTK101	2.00	BACHELOR	Introduction to reasoning, logic, and problem-solving skills. Students will learn how to evaluate arguments, identify fallacies, and develop clear and structured thinking.	\N	LEVEL1	Critical Thinking	6	1
17	2025-08-22 13:13:56.380512+00	\N	t	CTK201	2.00	BACHELOR	Introduction to reasoning, logic, and problem-solving skills. Students will learn how to evaluate arguments, identify fallacies, and develop clear and structured thinking.	\N	LEVEL2	Critical Thinking	6	1
18	2025-08-22 13:14:31.580863+00	\N	t	CTK301	2.00	BACHELOR	Introduction to reasoning, logic, and problem-solving skills. Students will learn how to evaluate arguments, identify fallacies, and develop clear and structured thinking.	\N	LEVEL3	Critical Thinking	6	1
\.


--
-- TOC entry 4918 (class 0 OID 108537)
-- Dependencies: 229
-- Data for Name: users; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.users (id, creation_date, last_modified_date, active, department, email, first_name, last_name, must_change_password, password, phone, role, username) FROM stdin;
1	2025-08-20 15:18:21.595869+00	\N	t	\N	teacher@example.com	Default	Teacher	f	$2a$10$5uCVzJ7XBJKAJEkcfp/iSeL4NQdSe4XzO4zt6930EtofFElSbAvtK	\N	TEACHER	teacher
2	2025-08-20 15:18:21.807059+00	\N	t	\N	admin@example.com	System	Administrator	f	$2a$10$GX8RAPjlFLG9d0J.jgNYX.UqQZ2XSR0BJ18e9JcyrFOykpPUKNSl.	\N	ADMIN	admin
3	2025-08-20 15:18:21.916426+00	\N	t	\N	student1@example.com	Student1	Level1	t	$2a$10$lCHlEUL5/qGdvZIAvNduHupdt9pY79bRz8fV0LmWGQ2GKV6JEPrHi	\N	STUDENT	student1
4	2025-08-20 15:18:22.056592+00	\N	t	\N	student2@example.com	Student2	Level2	t	$2a$10$nJ4WyyoEnwvETii/MPlWg.OQcChZiaHGv.w9CBBKpPPGmWX7DdZh2	\N	STUDENT	student2
5	2025-08-20 15:18:22.188234+00	\N	t	\N	student3@example.com	Student3	Level3	t	$2a$10$vtCUKrgHIQTj59eBx/BIje9B6oZ1uaCWpx296t/1dEPgvZJQ1oX/S	\N	STUDENT	student3
6	2025-08-20 15:18:22.330795+00	\N	t	\N	student4@example.com	Student4	Level4	t	$2a$10$GmQskUU3QdtzYXS97U9bduZUB2jvG9AQv7NpWpttG1HdwrUbFtKn2	\N	STUDENT	student4
7	2025-08-20 15:18:22.4997+00	\N	t	\N	student5@example.com	Student5	Level5	t	$2a$10$mngVVLnrqrbdsKwC0.2wyOtjPbe.2FJCRO61jvUpk8hriAjflGWIm	\N	STUDENT	student5
8	2025-08-20 15:18:22.620861+00	\N	t	\N	student@example.com	Default	Student	f	$2a$10$enW8eHu9pfg/HYAtG7TF6e.a78WCqkts4u7coiNiSrpBfm3hrG2jG	\N	STUDENT	student
52	2025-08-21 19:47:17.602851+00	\N	t	\N	marie.claire@example.com	Marie	Claire	t	$2a$10$jg4iyxJQov89BH2lsfP.EObn3XVki8bi65W2EaKcrBOeEMnItqCo.	\N	ADMIN	mclaire
53	2025-08-21 20:17:22.130933+00	\N	t	\N	john.doe@university.com	John	Doe	t	$2a$10$keHIizBUyoho/M/lFYzDWOho0qVF93gpFnltO5qoR6jmUL0e2WWnO	\N	TEACHER	jdoe
54	2025-08-22 08:15:56.232401+00	\N	t	\N	alice.smith@university.com	Alice	Smith	t	$2a$10$jCamgTkLeaCeiOwlGWUmTe9FUO0z/U49grfy5AX8P4Ha9WZwHWqlm	\N	TEACHER	asmith
55	2025-08-22 08:19:17.427554+00	\N	t	\N	paul.white@university.com	Paul	White	t	$2a$10$dQEqD/6CncWgylu0kfdIiO7o8KLPLi5GKNBkWlskTH4u8nDU1lZf6	\N	TEACHER	pwhite
56	2025-08-22 08:23:21.351254+00	\N	t	\N	julia.green@university.com	Julia	Green	t	$2a$10$I2ZiiV5eMK2CHpHibFnCXu/9H9IXiI7sfc4MH4IAW3PzBqMNx3cbi	\N	TEACHER	jgreen
57	2025-08-22 08:27:24.512409+00	\N	t	\N	khadim.ndoye@university.com	Khadim	Ndoye	t	$2a$10$0t/TUavkylKgeM39rn1idOzYa5cfOb7olizujuX9HSOgMCV//o5CS	\N	TEACHER	kndoye
58	2025-08-22 08:35:51.190548+00	\N	t	\N	michel.kalonji@university.com	Michel	Kalonji	t	$2a$10$NjatJgQmbUWoa3XvCrqKSe.jGl/EwnmzMaDbNEwSQh5OxY.oyirQi	\N	TEACHER	mkalonji
59	2025-08-22 08:37:08.988075+00	\N	t	\N	femi.okafor@university.com	Femi	Okafor	t	$2a$10$Xd1eNYVfXGM9vbwnYxQbzu9TmB0DTQ6RZnn7NIPV8FKO75pqNUpgO	\N	TEACHER	fokafor
60	2025-08-22 08:39:44.063085+00	\N	t	\N	leila.said@university.com	Leila	Said	t	$2a$10$MvTKGbpvN9qmrqjMcCrw1.wWI7N27GmZ/mEnR6.pZY3IjC87G21Pu	\N	TEACHER	lsaid
61	2025-08-22 08:41:22.420472+00	\N	t	\N	tidiane.kamara@university.com	Tidiane	Kamara	t	$2a$10$JcTWdVAOHz8ZY30NcAKar.9BeORu5S2FGG/eL/QN.kxgTQVnt9Xbi	\N	TEACHER	tkamara
62	2025-08-22 08:42:27.401995+00	\N	t	\N	nomsa.sibanda@university.com	Nomsa	Sibanda	t	$2a$10$taJWrjdHcf8VFrSAAJmDeeh8p5c65e9/UbQAvg0B3gOHzqPsfMjSm	\N	TEACHER	nsibanda
63	2025-08-22 08:43:43.920861+00	\N	t	\N	olivia.kone@university.com	Olivia	Koné	t	$2a$10$BG1gEtSUSrPnq9uKIF4CFutG1hckm8vG4Wm5xSaT414XyJBdEvxDC	\N	TEACHER	okone
64	2025-08-22 08:48:58.310406+00	\N	t	\N	omar.diallo@university.com	Omar	Diallo	t	$2a$10$2KUoxxVD2kcy8.NwdXMTpOsUjhRG6V5dQK4JpXGFMwnruqPd7ii6m	\N	TEACHER	odiallo
65	2025-08-22 08:50:13.033963+00	\N	t	\N	mariam.habiba@university.com	Mariam	Habiba	t	$2a$10$Lh6jZBFZ7TEQYe5g2q7Gb.o8njI2VxU1KMdhiZgtyDn2dFGWon4lO	\N	TEACHER	mhabiba
66	2025-08-22 08:50:58.92381+00	\N	t	\N	selam.kebede@university.com	Selam	Kebede	t	$2a$10$DWsPkl0HvCHTt1U2orgOpuwGTqX7BOsIx8jzFT9v9qcO1kBqvhFG6	\N	TEACHER	skebede
67	2025-08-22 08:52:02.288545+00	\N	t	\N	robert.mutiso@university.com	Robert	Mutiso	t	$2a$10$jp0pFzVAyPaOsCxc01bvDO6XUEYUSASkkepu7ctv6MNAe4hpNsG6q	\N	TEACHER	rmutiso
68	2025-08-22 08:52:41.323841+00	\N	t	\N	faith.mbeki@university.com	Faith	Mbeki	t	$2a$10$gWiCm61uytzBVJX1yknLFulgh8uEhDPGgtZJeqRvfq850ivpVpvrG	\N	TEACHER	fmbeki
69	2025-08-22 08:53:11.989331+00	\N	t	\N	yusuf.kamara@university.com	Yusuf	Kamara	t	$2a$10$4P9FDBl6qLnJxQOsZoYVLuetMQEFMUXdQ7TA4yf4m1l1eLknxVR5i	\N	TEACHER	ykamara
70	2025-08-22 10:20:58.746047+00	\N	t	\N	rita.banjo@student.university.com	Rita	Banjo	t	$2a$10$x/0XJ6z/JjSZfri4lUz4U./jn8Sx5mdBC19gZVE6Pg/B3F.gZKK1W	\N	STUDENT	MAT2025-101
71	2025-08-22 10:21:42.255067+00	\N	t	\N	victor.okoye@student.university.com	Victor	Okoye	t	$2a$10$WDSfTEiCbCou/qF.ge8jxedUD76utorLENin1i7TZTOkmwPPjyRUa	\N	STUDENT	MAT2025-102
72	2025-08-22 10:22:12.026408+00	\N	t	\N	sophie.mbaye@student.university.com	Sophie	Mbaye	t	$2a$10$aCOuHvM1hpWn3x1gDf0JgelrW9Cmnghk8TWtypTE7Tide3hDmULvS	\N	STUDENT	MAT2025-103
73	2025-08-22 10:22:44.656176+00	\N	t	\N	amina.koulibaly@student.university.com	Amina	Koulibaly	t	$2a$10$5xRdEo0wyDxeBf74Hk4GreAB3Z7ddt5RmRJibevMGmXUXGwOQu61W	\N	STUDENT	MAT2025-104
74	2025-08-22 10:23:20.430799+00	\N	t	\N	junior.mbanda@student.university.com	Junior	Mbanda	t	$2a$10$tsr3nSYPpau1UqRnvKerN.2MuzA1MWMfDjTTtIiZpX/ZSdbCIZ/Vq	\N	STUDENT	MAT2025-105
75	2025-08-22 10:23:46.156986+00	\N	t	\N	charlotte.nzinga@student.university.com	Charlotte	Nzinga	t	$2a$10$HFYlFhkKEiFSqw4kZGA3gO3k8Xxtc4wqZMnP2c.qBv79rpvwDDU8.	\N	STUDENT	MAT2025-106
78	2025-08-22 11:09:31.913278+00	\N	t	\N	julia.omoh@student.university.com	Julia	Omoh	t	$2a$10$JzuMBP67jRnrJ.mGNxynfuCaCQsYjMEougPQC4LGh2jPdWUZRUEGu	\N	STUDENT	MAT2025-201
79	2025-08-22 11:12:28.934538+00	\N	t	\N	thierry.badu@student.university.com	Thierry	Badu	t	$2a$10$Tm0xcBWCUmqKO6wMJ4TZguE4OiPcYkuHJJ9/3CG7UtNdpyyBciZSG	\N	STUDENT	MAT2025-202
80	2025-08-22 11:13:01.318016+00	\N	t	\N	amina.gaye@student.university.com	Amina	Gaye	t	$2a$10$RqUvvHCaiERBWxq7CohkFO.eVcEDJdSsbpy96MaLkAuRFhbD.JY/K	\N	STUDENT	MAT2025-203
81	2025-08-22 11:14:14.693537+00	\N	t	\N	kofi.kamara@student.university.com	Kofi	Kamara	t	$2a$10$96HCF2awZC7gzAiCruTP3.PPRh9Nb1pMFw.0DteBzps3n79PiHaXi	\N	STUDENT	MAT2025-204
82	2025-08-22 11:14:47.25714+00	\N	t	\N	mari.sylla@student.university.com	Mari	Sylla	t	$2a$10$nG36byPmw7D5XudXn5RR3e5CFso8drvxp4bX0P.rEXqkuF6FjujNi	\N	STUDENT	MAT2025-205
83	2025-08-22 11:15:40.204724+00	\N	t	\N	charlotte.kone@student.university.com	Charlotte	Kone	t	$2a$10$NcrDqqWtTKH5SYmYq3DYB.SrJZxrNz1x7iIAdB..MVU0vQ9wnX906	\N	STUDENT	MAT2025-206
84	2025-08-22 11:23:48.636466+00	\N	t	\N	amina.wade@student.university.com	Amina	Wade	t	$2a$10$mDBF93kIZo8UcUE.IPLe2uhRIHiHlGKVluV2nJkTJhqXfUOpJ3x7O	\N	STUDENT	MAT2025-301
85	2025-08-22 11:24:22.47845+00	\N	t	\N	thierry.kabira@student.university.com	Thierry	Kabira	t	$2a$10$FygVKRDFqPRx13h7GDoNw.VArkHOVxzGif.qIJL8jwpPP8Dp9J1zW	\N	STUDENT	MAT2025-302
86	2025-08-22 11:24:50.264004+00	\N	t	\N	bola.funmi@student.university.com	Bola	Funmi	t	$2a$10$MHH7BmlaO8ue9sQKExNZXe3NtMJ.LQOuIq5wSdhYyJ2PDGcgDhIE2	\N	STUDENT	MAT2025-303
87	2025-08-22 11:25:13.569232+00	\N	t	\N	mario.kouame@student.university.com	Mario	Kouame	t	$2a$10$jEWC9VL./o009D1FgzQ1m.GMoWbAiyRi3OI8VhRzy0ortV.JZhw6y	\N	STUDENT	MAT2025-304
88	2025-08-22 11:25:52.788541+00	\N	t	\N	nora.simbe@student.university.com	Nora	Simbe	t	$2a$10$FH4k6TFoe/BZ8SSFBSbiyO/HMYDg9G.3STBXF1rwRMwNaE9DE6hby	\N	STUDENT	MAT2025-305
89	2025-08-22 11:26:15.074367+00	\N	t	\N	charlotte.kouadio@student.university.com	Charlotte	Kouadio	t	$2a$10$tD0/JkFyznD6XjAEueG28.K3sbR2zg1KDWw28yqPY1b8gj3HGywKi	\N	STUDENT	MAT2025-306
\.


--
-- TOC entry 4938 (class 0 OID 0)
-- Dependencies: 217
-- Name: departments_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.departments_id_seq', 6, true);


--
-- TOC entry 4939 (class 0 OID 0)
-- Dependencies: 240
-- Name: grade_claim_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.grade_claim_seq', 1, false);


--
-- TOC entry 4940 (class 0 OID 0)
-- Dependencies: 241
-- Name: grade_claims_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.grade_claims_id_seq', 1, false);


--
-- TOC entry 4941 (class 0 OID 0)
-- Dependencies: 230
-- Name: grade_report_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.grade_report_seq', 1, false);


--
-- TOC entry 4942 (class 0 OID 0)
-- Dependencies: 231
-- Name: grades_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.grades_seq', 101, true);


--
-- TOC entry 4943 (class 0 OID 0)
-- Dependencies: 232
-- Name: grading_window_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.grading_window_seq', 1, false);


--
-- TOC entry 4944 (class 0 OID 0)
-- Dependencies: 222
-- Name: invite_token_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.invite_token_id_seq', 1, false);


--
-- TOC entry 4945 (class 0 OID 0)
-- Dependencies: 233
-- Name: report_record_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.report_record_seq', 1, false);


--
-- TOC entry 4946 (class 0 OID 0)
-- Dependencies: 234
-- Name: semesters_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.semesters_seq', 51, true);


--
-- TOC entry 4947 (class 0 OID 0)
-- Dependencies: 235
-- Name: student_info_requests_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.student_info_requests_seq', 1, false);


--
-- TOC entry 4948 (class 0 OID 0)
-- Dependencies: 236
-- Name: students_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.students_seq', 151, true);


--
-- TOC entry 4949 (class 0 OID 0)
-- Dependencies: 237
-- Name: subject_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.subject_seq', 51, true);


--
-- TOC entry 4950 (class 0 OID 0)
-- Dependencies: 238
-- Name: users_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.users_seq', 101, true);


--
-- TOC entry 4713 (class 2606 OID 108469)
-- Name: departments departments_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.departments
    ADD CONSTRAINT departments_pkey PRIMARY KEY (id);


--
-- TOC entry 4743 (class 2606 OID 108610)
-- Name: grade_claim grade_claim_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.grade_claim
    ADD CONSTRAINT grade_claim_pkey PRIMARY KEY (id);


--
-- TOC entry 4745 (class 2606 OID 116665)
-- Name: grade_claims grade_claims_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.grade_claims
    ADD CONSTRAINT grade_claims_pkey PRIMARY KEY (id);


--
-- TOC entry 4717 (class 2606 OID 108476)
-- Name: grade_report grade_report_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.grade_report
    ADD CONSTRAINT grade_report_pkey PRIMARY KEY (id);


--
-- TOC entry 4719 (class 2606 OID 108484)
-- Name: grades grades_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.grades
    ADD CONSTRAINT grades_pkey PRIMARY KEY (id);


--
-- TOC entry 4721 (class 2606 OID 108489)
-- Name: grading_window grading_window_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.grading_window
    ADD CONSTRAINT grading_window_pkey PRIMARY KEY (id);


--
-- TOC entry 4723 (class 2606 OID 108498)
-- Name: invite_token invite_token_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.invite_token
    ADD CONSTRAINT invite_token_pkey PRIMARY KEY (id);


--
-- TOC entry 4727 (class 2606 OID 108505)
-- Name: report_record report_record_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.report_record
    ADD CONSTRAINT report_record_pkey PRIMARY KEY (id);


--
-- TOC entry 4729 (class 2606 OID 108510)
-- Name: semesters semesters_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.semesters
    ADD CONSTRAINT semesters_pkey PRIMARY KEY (id);


--
-- TOC entry 4731 (class 2606 OID 108518)
-- Name: student_info_requests student_info_requests_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.student_info_requests
    ADD CONSTRAINT student_info_requests_pkey PRIMARY KEY (id);


--
-- TOC entry 4733 (class 2606 OID 108527)
-- Name: students students_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.students
    ADD CONSTRAINT students_pkey PRIMARY KEY (id);


--
-- TOC entry 4737 (class 2606 OID 108536)
-- Name: subject subject_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.subject
    ADD CONSTRAINT subject_pkey PRIMARY KEY (id);


--
-- TOC entry 4735 (class 2606 OID 108550)
-- Name: students uk1psraxut9bwn2why6ex4xf1en; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.students
    ADD CONSTRAINT uk1psraxut9bwn2why6ex4xf1en UNIQUE (matricule);


--
-- TOC entry 4725 (class 2606 OID 108548)
-- Name: invite_token uk60k2cybcnd18p0cnf0e5sssb6; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.invite_token
    ADD CONSTRAINT uk60k2cybcnd18p0cnf0e5sssb6 UNIQUE (token);


--
-- TOC entry 4715 (class 2606 OID 108546)
-- Name: departments ukj6cwks7xecs5jov19ro8ge3qk; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.departments
    ADD CONSTRAINT ukj6cwks7xecs5jov19ro8ge3qk UNIQUE (name);


--
-- TOC entry 4739 (class 2606 OID 108552)
-- Name: users ukr43af9ap4edm43mmtq01oddj6; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.users
    ADD CONSTRAINT ukr43af9ap4edm43mmtq01oddj6 UNIQUE (username);


--
-- TOC entry 4741 (class 2606 OID 108544)
-- Name: users users_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.users
    ADD CONSTRAINT users_pkey PRIMARY KEY (id);


--
-- TOC entry 4757 (class 2606 OID 116671)
-- Name: grade_claims fk2kbul9dstw4uo15gc5tomfkni; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.grade_claims
    ADD CONSTRAINT fk2kbul9dstw4uo15gc5tomfkni FOREIGN KEY (grade_id) REFERENCES public.grades(id);


--
-- TOC entry 4746 (class 2606 OID 108572)
-- Name: grades fk384e8h2qimc9qlnh970ytgdr5; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.grades
    ADD CONSTRAINT fk384e8h2qimc9qlnh970ytgdr5 FOREIGN KEY (id_students) REFERENCES public.students(id);


--
-- TOC entry 4752 (class 2606 OID 108597)
-- Name: subject fk4b66tj7yip7jmo922vvy6bw4y; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.subject
    ADD CONSTRAINT fk4b66tj7yip7jmo922vvy6bw4y FOREIGN KEY (id_semester) REFERENCES public.semesters(id);


--
-- TOC entry 4754 (class 2606 OID 108612)
-- Name: grade_claim fk89upq1hqsa0g35ml01y3ss7e3; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.grade_claim
    ADD CONSTRAINT fk89upq1hqsa0g35ml01y3ss7e3 FOREIGN KEY (id_grade) REFERENCES public.grades(id);


--
-- TOC entry 4758 (class 2606 OID 116666)
-- Name: grade_claims fk8b4k9pw7j018vpks0ns5wmsp0; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.grade_claims
    ADD CONSTRAINT fk8b4k9pw7j018vpks0ns5wmsp0 FOREIGN KEY (created_by_id) REFERENCES public.users(id);


--
-- TOC entry 4755 (class 2606 OID 108622)
-- Name: grade_claim fk9x40h9g78vq6p16ifrskjcmfl; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.grade_claim
    ADD CONSTRAINT fk9x40h9g78vq6p16ifrskjcmfl FOREIGN KEY (id_student) REFERENCES public.students(id);


--
-- TOC entry 4756 (class 2606 OID 108617)
-- Name: grade_claim fkanjtrx9f1rrxr0dmjfwl0oksb; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.grade_claim
    ADD CONSTRAINT fkanjtrx9f1rrxr0dmjfwl0oksb FOREIGN KEY (id_semester) REFERENCES public.semesters(id);


--
-- TOC entry 4759 (class 2606 OID 116681)
-- Name: grade_claims fkc1rbjpi3wpf5ihn0h81pygtnc; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.grade_claims
    ADD CONSTRAINT fkc1rbjpi3wpf5ihn0h81pygtnc FOREIGN KEY (student_id) REFERENCES public.students(id);


--
-- TOC entry 4751 (class 2606 OID 108587)
-- Name: student_info_requests fkfawh6psw2f3yivjbpciph35nh; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.student_info_requests
    ADD CONSTRAINT fkfawh6psw2f3yivjbpciph35nh FOREIGN KEY (student_id) REFERENCES public.students(id);


--
-- TOC entry 4747 (class 2606 OID 108562)
-- Name: grades fkfrqv6jj26ycmq0uqihsmofd9w; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.grades
    ADD CONSTRAINT fkfrqv6jj26ycmq0uqihsmofd9w FOREIGN KEY (id_users) REFERENCES public.users(id);


--
-- TOC entry 4748 (class 2606 OID 108577)
-- Name: grades fkippbjcacm6nkn7hon47r53l99; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.grades
    ADD CONSTRAINT fkippbjcacm6nkn7hon47r53l99 FOREIGN KEY (id_subject) REFERENCES public.subject(id);


--
-- TOC entry 4750 (class 2606 OID 108582)
-- Name: grading_window fkmkan866y61akk4qim8e74d3dj; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.grading_window
    ADD CONSTRAINT fkmkan866y61akk4qim8e74d3dj FOREIGN KEY (id_semester) REFERENCES public.semesters(id);


--
-- TOC entry 4753 (class 2606 OID 108592)
-- Name: subject fkqym877gemkcwuhmjmbuokvf6f; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.subject
    ADD CONSTRAINT fkqym877gemkcwuhmjmbuokvf6f FOREIGN KEY (department_id) REFERENCES public.departments(id);


--
-- TOC entry 4749 (class 2606 OID 108567)
-- Name: grades fks0yeww9160sohy3wpgmt7dve; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.grades
    ADD CONSTRAINT fks0yeww9160sohy3wpgmt7dve FOREIGN KEY (id_semester) REFERENCES public.semesters(id);


--
-- TOC entry 4760 (class 2606 OID 116676)
-- Name: grade_claims fkteaqiirgxcnndhnx4ljcoc60h; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.grade_claims
    ADD CONSTRAINT fkteaqiirgxcnndhnx4ljcoc60h FOREIGN KEY (semester_id) REFERENCES public.semesters(id);


-- Completed on 2025-08-22 17:20:47

--
-- PostgreSQL database dump complete
--

