package com.university.ManageNotes.service;

import com.university.ManageNotes.dto.Request.ReportRequest;
import com.university.ManageNotes.dto.Response.ReportResponse;
import com.university.ManageNotes.model.Grades;
import com.university.ManageNotes.model.ReportRecord;
import com.university.ManageNotes.model.Students;
import com.university.ManageNotes.model.Users;
import com.university.ManageNotes.repository.*;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;

import java.io.IOException;
import java.nio.file.Files;
import java.nio.file.Path;
import java.nio.file.Paths;
import java.time.Instant;
import java.util.List;

@Service
@Transactional
public class ReportService {

    @Autowired
    private AuthService authService;

    @Autowired
    private StudentRepository studentRepository;

    @Autowired
    private SubjectRepository subjectRepository;

    @Autowired
    private SemesterRepository semesterRepository;

    @Autowired
    private GradeRepository gradeRepository;

    @Autowired
    private ReportRecordRepository reportRecordRepository;

    @Autowired
    private EmailService emailService;

    private com.university.ManageNotes.dto.Response.GradeResponse mapGrade(Grades grade) {
        com.university.ManageNotes.dto.Response.GradeResponse resp = new com.university.ManageNotes.dto.Response.GradeResponse();
        resp.setId(grade.getId());
        resp.setStudentId(grade.getStudent().getId());
        resp.setStudentName(grade.getStudent().getFirstName() + " " + grade.getStudent().getLastName());
        resp.setSubjectId(grade.getSubject().getId());
        resp.setSubjectName(grade.getSubject().getName());
        resp.setSubjectCode(grade.getSubject().getCode());
        if (grade.getSemesters() != null) {
            resp.setSemesterId(grade.getSemesters().getId());
            resp.setSemesterName(grade.getSemesters().getName());
        }
        resp.setValue(grade.getValue());
        resp.setType(grade.getType());
        resp.setComments(grade.getComments());
        resp.setEnteredBy(grade.getEnteredBy().getId());
        resp.setEnteredByName(grade.getEnteredBy().getFirstName() + " " + grade.getEnteredBy().getLastName());
        resp.setCreatedDate(grade.getCreatedDate());
        resp.setLastModifiedDate(grade.getLastModifiedDate());
        return resp;
    }

    public byte[] generatePDFReport(Students student, List<Grades> grades, String reportTitle) throws IOException {
        // Use PDFBox to create a basic PDF so that viewers recognise the file
        try (var document = new org.apache.pdfbox.pdmodel.PDDocument();
             var out = new java.io.ByteArrayOutputStream()) {
            var page = new org.apache.pdfbox.pdmodel.PDPage();
            document.addPage(page);

            var font = org.apache.pdfbox.pdmodel.font.PDType1Font.HELVETICA;
            try (var content = new org.apache.pdfbox.pdmodel.PDPageContentStream(document, page)) {
                content.beginText();
                content.setFont(font, 14);
                content.newLineAtOffset(50, 750);
                content.showText(reportTitle);
                content.newLineAtOffset(0, -30);
                if (student != null) {
                    content.showText("Student: " + student.getFirstName() + " " + student.getLastName());
                    content.newLineAtOffset(0, -20);
                    String semesterName = !grades.isEmpty() ? grades.get(0).getSemesters().getName() : "N/A";
                    String subjectName = !grades.isEmpty() ? grades.get(0).getSubject().getName() : "N/A";
                    content.showText("Semester: " + semesterName);
                    content.newLineAtOffset(0, -20);
                    content.showText("Subject: " + subjectName);
                    content.newLineAtOffset(0, -30);
                }
                if (grades != null && !grades.isEmpty()) {
                    content.showText("Type  |  Score");
                    for (Grades g : grades) {
                        content.newLineAtOffset(0, -16);
                        content.showText(g.getGradeType().name() + "    " + g.getValue());
                    }
                }
                content.endText();
            }
            document.save(out);
            return out.toByteArray();
        }
    }

    private String generatePDFContent(Students student, List<Grades> grades, String reportTitle, Users currentUser) {
        StringBuilder content = new StringBuilder();
        content.append("=== ").append(reportTitle).append(" ===\n");
        content.append("Student: ").append(student.getFirstName()).append(" ").append(student.getLastName()).append("\n");
        content.append("Generated by: ").append(currentUser.getFirstName()).append(" ").append(currentUser.getLastName()).append("\n\n");

        content.append("GRADES:\n");
        for (Grades grade : grades) {
            content.append("Subject: ").append(grade.getSubject().getName()).append("\n");
            content.append("Value: ").append(grade.getValue()).append("\n");
            content.append("Type: ").append(grade.getGradeType().name()).append("\n");
            content.append("Semester: ").append(grade.getSemesters().getName()).append("\n");
            content.append("Comments: ").append(grade.getComments()).append("\n");
            content.append("------------------------\n");
        }

        return content.toString();
    }

    public ReportResponse generateStudentReport(Long studentId, ReportRequest reportRequest) {
        ReportResponse response = new ReportResponse();
        try {
            // fetch entities
            var studentOpt = studentRepository.findById(studentId);
            var semesterOpt = semesterRepository.findById(reportRequest.getSemesterId());
            if (studentOpt.isEmpty() || semesterOpt.isEmpty())
                throw new RuntimeException("Student or Semester not found");
            var student = studentOpt.get();
            var semester = semesterOpt.get();

            // fetch grades
            List<Grades> grades = gradeRepository.findByStudentIdAndSemesterId(studentId, reportRequest.getSemesterId());

            // map detailed grades
            java.util.List<com.university.ManageNotes.dto.Response.GradeResponse> gradeDtos = grades.stream().map(this::mapGrade).toList();
            response.setGrades(gradeDtos);

            // compute semester average based on distinct subjects (one score per subject)
            java.util.Map<Long, java.util.DoubleSummaryStatistics> subjectStats = grades.stream()
                    .collect(java.util.stream.Collectors.groupingBy(g -> g.getSubject().getId(),
                            java.util.stream.Collectors.summarizingDouble(com.university.ManageNotes.model.Grades::getValue)));
            double semesterAvg = 0;
            if (!subjectStats.isEmpty()) {
                double totalSubjectScores = subjectStats.values().stream().mapToDouble(java.util.DoubleSummaryStatistics::getAverage).sum();
                semesterAvg = Math.round((totalSubjectScores / subjectStats.size()) * 100.0) / 100.0;
            }
            double gpa = semesterAvg;
            response.setGpa(gpa);

            // compute credits earned (validated) for the semester based on distinct subjects >=10
            int creditsEarned = subjectStats.entrySet().stream()
                    .filter(e -> e.getValue().getAverage() >= 10)
                    .map(e -> grades.stream().filter(g -> g.getSubject().getId().equals(e.getKey())).findFirst().get().getSubject().getCredits().intValue())
                    .reduce(0, Integer::sum);
            response.setCreditsEarned(creditsEarned);

            // fill response
            response.setStudentId(studentId);
            response.setStudentName(student.getFirstName() + " " + student.getLastName());
            response.setLevel(student.getLevel() != null ? student.getLevel().name() : null);
            response.setSemesterId(semester.getId());
            response.setSemesterName(semester.getName());
            response.setGpa(gpa);
            // compute annual average across two semesters
            var semesters = semesterRepository.findAll();
            if (semesters.size() >= 2) {
                var sem1 = semesters.get(0);
                var sem2 = semesters.get(1);
                var gradesS1 = gradeRepository.findByStudentIdAndSemesterId(studentId, sem1.getId());
                var gradesS2 = gradeRepository.findByStudentIdAndSemesterId(studentId, sem2.getId());

                // compute averages per semester using distinct subjects
                java.util.function.Function<java.util.List<com.university.ManageNotes.model.Grades>, java.lang.Double> calcAvg = list -> {
                    if (list.isEmpty()) return 0.0;
                    java.util.Map<Long, java.util.DoubleSummaryStatistics> stats = list.stream().collect(java.util.stream.Collectors.groupingBy(g -> g.getSubject().getId(), java.util.stream.Collectors.summarizingDouble(com.university.ManageNotes.model.Grades::getValue)));
                    double tot = stats.values().stream().mapToDouble(java.util.DoubleSummaryStatistics::getAverage).sum();
                    return tot / stats.size();
                };
                double avgS1 = calcAvg.apply(gradesS1);
                double avgS2 = calcAvg.apply(gradesS2);

                double annualAvg = ((avgS1 + avgS2) / 2.0);
                response.setAnnualAverage(Math.round(annualAvg * 100.0)/100.0);

                // compute academic-year credits validated (>=10 per subject)
                java.util.Map<Long,Integer> subjectCreditsMap = new java.util.HashMap<>();
                java.util.stream.Stream.concat(gradesS1.stream(), gradesS2.stream())
                        .forEach(g -> subjectCreditsMap.putIfAbsent(g.getSubject().getId(), g.getSubject().getCredits().intValue()));
                java.util.Set<Long> validatedSubjects = java.util.stream.Stream.concat(gradesS1.stream(), gradesS2.stream())
                        .collect(java.util.stream.Collectors.groupingBy(g -> g.getSubject().getId(), java.util.stream.Collectors.averagingDouble(com.university.ManageNotes.model.Grades::getValue)))
                        .entrySet().stream().filter(e -> e.getValue() >= 10).map(java.util.Map.Entry::getKey).collect(java.util.stream.Collectors.toSet());
                int creditsYear = validatedSubjects.stream().map(subjectCreditsMap::get).reduce(0, Integer::sum);
                response.setCreditsEarned(creditsYear);

                // promotion rule: at least 55 credits out of 60 and annual average >=10
                response.setStatus((creditsYear >= 55 && response.getAnnualAverage() >= 10) ? "PROMOTED" : "RETAKE");

                response.setReportType("STUDENT_GRADES");
                response.setCreatedDate(Instant.now());
                Users currentUser = authService.getCurrentUser();
                response.setGeneratedBy(currentUser.getId());
                response.setGeneratedByName(currentUser.getFirstName() + " " + currentUser.getLastName());

                if (Boolean.TRUE.equals(reportRequest.getIncludePdf())) {
                    // generate pdf
                    byte[] pdf = generatePDFReport(student, grades, "Student Report");
                    Path dir = Paths.get("generated-reports");
                    Files.createDirectories(dir);
                    String fileName = "student_" + studentId + "_sem_" + semester.getId() + "_" + Instant.now().toEpochMilli() + ".pdf";
                    Path filePath = dir.resolve(fileName);
                    Files.write(filePath, pdf);
                    response.setPdfPath(filePath.toString());
                    response.setDownloadUrl("/files/" + fileName);
                    response.setLastModifiedDate(Instant.now());

                    // email to parent/student
                    try {
                        emailService.sendMessageWithAttachment(
                                student.getEmail(),
                                "Grade Report",
                                "Dear Parent,\n\nPlease find attached the latest grade report for " + student.getFirstName() + " " + student.getLastName() + ".\n\nRegards", pdf, fileName);
                    } catch (Exception ignored) {}

                    // Persist report record in database
                    ReportRecord record = new ReportRecord();
                    record.setStudentId(response.getStudentId());
                    record.setSemesterId(response.getSemesterId());
                    record.setSubjectId(response.getSubjectId());
                    record.setReportType(response.getReportType());
                    record.setGpa(response.getGpa());
                    record.setStatus(response.getStatus());
                    record.setPdfPath(response.getPdfPath());
                    record.setDownloadUrl(response.getDownloadUrl());
                    record.setGeneratedBy(response.getGeneratedBy());
                    record.setLastModifiedDate(response.getLastModifiedDate());
                    ReportRecord saved = reportRecordRepository.save(record);
                    reportRecordRepository.flush();
                    response.setId(saved.getId());
                }

                return response;
            }

            // if semesters less than 2, still set some defaults and return
            response.setReportType("STUDENT_GRADES");
            response.setCreatedDate(Instant.now());
            Users currentUser = authService.getCurrentUser();
            response.setGeneratedBy(currentUser.getId());
            response.setGeneratedByName(currentUser.getFirstName() + " " + currentUser.getLastName());

            return response;
        } catch (Exception e) {
            response.setSuccess(false);
            response.setMessage("Failed to generate report: " + e.getMessage());
            return response;
        }
    }

    public ReportResponse generateClassReport(Long classId, ReportRequest reportRequest) {
        try {
            // Logic to generate class report
            ReportResponse response = new ReportResponse();
            response.setReportType("CLASS_GRADES");
            response.setSuccess(true);
            response.setMessage("Class report generated successfully");

            return response;
        } catch (Exception e) {
            ReportResponse response = new ReportResponse();
            response.setSuccess(false);
            response.setMessage("Failed to generate class report: " + e.getMessage());
            return response;
        }
    }

    public ReportResponse generateSubjectReport(Long subjectId, ReportRequest reportRequest) {
        ReportResponse response = new ReportResponse();
        try {
            var studentOpt = studentRepository.findById(reportRequest.getStudentId());
            var semesterOpt = semesterRepository.findById(reportRequest.getSemesterId());
            var subjectOpt = subjectRepository.findById(subjectId);
            if (studentOpt.isEmpty() || semesterOpt.isEmpty() || subjectOpt.isEmpty())
                throw new RuntimeException("Student/Semester/Subject not found");
            var student = studentOpt.get();
            var semester = semesterOpt.get();
            var subject = subjectOpt.get();

            List<Grades> grades = gradeRepository.findByStudentIdAndSubjectId(reportRequest.getStudentId(), subjectId);
            if (!grades.isEmpty()) {
                grades = grades.stream().filter(g -> g.getSemesters() != null && g.getSemesters().getId().equals(reportRequest.getSemesterId())).toList();
            }

            double gpa = 0;
            if (!grades.isEmpty()) {
                double total = grades.stream().mapToDouble(Grades::getValue).sum();
                gpa = Math.round((total / grades.size()) * 100.0) / 100.0;
            }

            // map grades
            java.util.List<com.university.ManageNotes.dto.Response.GradeResponse> gradeDtos = grades.stream().map(this::mapGrade).toList();
            response.setGrades(gradeDtos);

            int creditsEarned = grades.stream()
                    .filter(g -> g.getValue() >= 10)
                    .map(g -> g.getSubject().getCredits().intValue())
                    .reduce(0, Integer::sum);

            response.setStudentId(student.getId());
            response.setStudentName(student.getFirstName() + " " + student.getLastName());
            response.setSemesterId(semester.getId());
            response.setSemesterName(semester.getName());
            response.setSubjectId(subject.getId());
            response.setSubjectName(subject.getName());
            response.setGpa(gpa);
            response.setStatus(creditsEarned >= 55 ? "PROMOTED" : "RETAKE");
            response.setReportType("SUBJECT_GRADES");
            response.setCreatedDate(Instant.now());
            Users currentUser = authService.getCurrentUser();
            response.setGeneratedBy(currentUser.getId());
            response.setGeneratedByName(currentUser.getFirstName() + " " + currentUser.getLastName());

            // generate pdf
            byte[] pdf = generatePDFReport(student, grades, "Subject Report");
            Path dir = Paths.get("generated-reports");
            Files.createDirectories(dir);
            String fileName = "student_" + student.getId() + "_subject_" + subjectId + "_" + Instant.now().toEpochMilli() + ".pdf";
            Path filePath = dir.resolve(fileName);
            Files.write(filePath, pdf);
            response.setPdfPath(filePath.toString());
            response.setDownloadUrl("/files/" + fileName);
            response.setLastModifiedDate(response.getCreatedDate());

            try {
                emailService.sendMessageWithAttachment(
                        student.getEmail(),
                        "Subject Report",
                        "Dear Parent,\n\nAttached is the subject report for " + student.getFirstName() + " " + student.getLastName() + ".\n\nRegards", pdf, fileName);
            } catch (Exception ignored) {}

            // Persist record similar to student report
            ReportRecord record = new ReportRecord();
            record.setStudentId(response.getStudentId());
            record.setSemesterId(response.getSemesterId());
            record.setSubjectId(response.getSubjectId());
            record.setReportType(response.getReportType());
            record.setGpa(response.getGpa());
            record.setStatus(response.getStatus());
            record.setPdfPath(response.getPdfPath());
            record.setDownloadUrl(response.getDownloadUrl());
            record.setGeneratedBy(response.getGeneratedBy());
            record.setLastModifiedDate(response.getLastModifiedDate());
            ReportRecord saved = reportRecordRepository.save(record);
            reportRecordRepository.flush();
            response.setId(saved.getId());

            response.setSuccess(true);
            response.setMessage("Subject report generated successfully");
            return response;
        } catch (Exception e) {
            response.setSuccess(false);
            response.setMessage("Failed to generate subject report: " + e.getMessage());
            return response;
        }
    }

    public byte[] exportToExcel(List<Grades> grades) throws IOException {
        // Simulate Excel export
        StringBuilder csvContent = new StringBuilder();
        csvContent.append("Student,Subject,Grade,Type,Semester\n");

        for (Grades grade : grades) {
            csvContent.append(grade.getStudent().getFirstName()).append(" ").append(grade.getStudent().getLastName()).append(",");
            csvContent.append(grade.getSubject().getName()).append(",");
            csvContent.append(grade.getValue()).append(",");
            csvContent.append(grade.getGradeType().name()).append(",");
            csvContent.append(grade.getSemesters().getName()).append("\n");
        }

        return csvContent.toString().getBytes();
    }

    public ReportResponse getStudentYearSummary(Long studentId) {
        ReportRequest dummy = new ReportRequest();
        dummy.setStudentId(studentId);
        // we assume semesters table has at least two entries ordered
        var semesters = semesterRepository.findAll();
        if (semesters.size() >= 2) {
            dummy.setSemesterId(semesters.get(0).getId()); // any non-null to satisfy validation
        }
        dummy.setIncludePdf(false);
        return generateStudentReport(studentId, dummy);
    }
}
