--
-- PostgreSQL database dump
--

-- Dumped from database version 17.5 (Ubuntu 17.5-1.pgdg24.04+1)
-- Dumped by pg_dump version 17.5 (Ubuntu 17.5-1.pgdg24.04+1)

-- Started on 2025-08-22 14:18:40 WAT

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET transaction_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- TOC entry 238 (class 1259 OID 16942)
-- Name: departments; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.departments (
    id bigint NOT NULL,
    name character varying(100) NOT NULL
);


ALTER TABLE public.departments OWNER TO postgres;

--
-- TOC entry 237 (class 1259 OID 16941)
-- Name: departments_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.departments ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.departments_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 241 (class 1259 OID 16975)
-- Name: grade_claim; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.grade_claim (
    id bigint NOT NULL,
    creation_date timestamp(6) with time zone NOT NULL,
    last_modified_date timestamp(6) with time zone,
    cause character varying(255),
    description character varying(1000),
    period_label character varying(255),
    requested_score double precision,
    resolved_at timestamp(6) without time zone,
    status character varying(255),
    teacher_comment character varying(1000),
    id_grade bigint,
    id_semester bigint,
    id_student bigint,
    CONSTRAINT grade_claim_status_check CHECK (((status)::text = ANY ((ARRAY['PENDING'::character varying, 'APPROVED'::character varying, 'REJECTED'::character varying])::text[])))
);


ALTER TABLE public.grade_claim OWNER TO postgres;

--
-- TOC entry 242 (class 1259 OID 16983)
-- Name: grade_claim_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

CREATE SEQUENCE public.grade_claim_seq
    START WITH 1
    INCREMENT BY 50
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER SEQUENCE public.grade_claim_seq OWNER TO postgres;

--
-- TOC entry 244 (class 1259 OID 17000)
-- Name: grade_claims; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.grade_claims (
    id bigint NOT NULL,
    created_at timestamp(6) without time zone,
    rejection_reason character varying(255),
    resolved_at timestamp(6) without time zone,
    status character varying(255),
    cause text,
    description text,
    period_label character varying(255),
    requested_score double precision NOT NULL,
    teacher_comment text,
    created_by_id bigint,
    grade_id bigint NOT NULL,
    semester_id bigint,
    student_id bigint NOT NULL,
    CONSTRAINT grade_claims_status_check CHECK (((status)::text = ANY ((ARRAY['PENDING'::character varying, 'APPROVED'::character varying, 'REJECTED'::character varying])::text[])))
);


ALTER TABLE public.grade_claims OWNER TO postgres;

--
-- TOC entry 243 (class 1259 OID 16999)
-- Name: grade_claims_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

CREATE SEQUENCE public.grade_claims_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER SEQUENCE public.grade_claims_id_seq OWNER TO postgres;

--
-- TOC entry 3595 (class 0 OID 0)
-- Dependencies: 243
-- Name: grade_claims_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: postgres
--

ALTER SEQUENCE public.grade_claims_id_seq OWNED BY public.grade_claims.id;


--
-- TOC entry 217 (class 1259 OID 16822)
-- Name: grade_report; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.grade_report (
    id bigint NOT NULL,
    creation_date timestamp(6) with time zone NOT NULL,
    last_modified_date timestamp(6) with time zone,
    gpa double precision,
    id_semesters bigint,
    id_students bigint,
    pdf_path character varying(255),
    status character varying(255)
);


ALTER TABLE public.grade_report OWNER TO postgres;

--
-- TOC entry 224 (class 1259 OID 16875)
-- Name: grade_report_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

CREATE SEQUENCE public.grade_report_seq
    START WITH 1
    INCREMENT BY 50
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER SEQUENCE public.grade_report_seq OWNER TO postgres;

--
-- TOC entry 218 (class 1259 OID 16829)
-- Name: grades; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.grades (
    id bigint NOT NULL,
    creation_date timestamp(6) with time zone NOT NULL,
    last_modified_date timestamp(6) with time zone,
    coefficient double precision,
    comments character varying(255),
    grade_type character varying(255),
    value double precision,
    id_users bigint,
    id_semester bigint,
    id_students bigint,
    id_subject bigint,
    period_label character varying(255),
    max_value double precision,
    CONSTRAINT grades_grade_type_check CHECK (((grade_type)::text = ANY ((ARRAY['ASSIGNMENT'::character varying, 'EXAM'::character varying, 'QUIZ'::character varying, 'PROJECT'::character varying])::text[])))
);


ALTER TABLE public.grades OWNER TO postgres;

--
-- TOC entry 225 (class 1259 OID 16876)
-- Name: grades_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

CREATE SEQUENCE public.grades_seq
    START WITH 1
    INCREMENT BY 50
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER SEQUENCE public.grades_seq OWNER TO postgres;

--
-- TOC entry 235 (class 1259 OID 16930)
-- Name: grading_window; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.grading_window (
    id bigint NOT NULL,
    creation_date timestamp(6) with time zone NOT NULL,
    last_modified_date timestamp(6) with time zone,
    active boolean,
    end_date date,
    name character varying(255),
    start_date date,
    id_semester bigint
);


ALTER TABLE public.grading_window OWNER TO postgres;

--
-- TOC entry 236 (class 1259 OID 16935)
-- Name: grading_window_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

CREATE SEQUENCE public.grading_window_seq
    START WITH 1
    INCREMENT BY 50
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER SEQUENCE public.grading_window_seq OWNER TO postgres;

--
-- TOC entry 234 (class 1259 OID 16911)
-- Name: invite_token; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.invite_token (
    id bigint NOT NULL,
    claimed boolean NOT NULL,
    expires_at timestamp(6) with time zone NOT NULL,
    role character varying(255) NOT NULL,
    token character varying(255) NOT NULL,
    CONSTRAINT invite_token_role_check CHECK (((role)::text = ANY ((ARRAY['ADMIN'::character varying, 'STUDENT'::character varying, 'TEACHER'::character varying])::text[])))
);


ALTER TABLE public.invite_token OWNER TO postgres;

--
-- TOC entry 233 (class 1259 OID 16910)
-- Name: invite_token_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.invite_token ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.invite_token_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 231 (class 1259 OID 16902)
-- Name: report_record; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.report_record (
    id bigint NOT NULL,
    creation_date timestamp(6) with time zone NOT NULL,
    last_modified_date timestamp(6) with time zone,
    class_id bigint,
    download_url character varying(255),
    generated_by bigint,
    gpa double precision,
    pdf_path character varying(255),
    report_type character varying(50),
    semester_id bigint,
    status character varying(255),
    student_id bigint,
    subject_id bigint,
    academic_year character varying(255),
    faculty character varying(255),
    university_name character varying(255)
);


ALTER TABLE public.report_record OWNER TO postgres;

--
-- TOC entry 232 (class 1259 OID 16909)
-- Name: report_record_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

CREATE SEQUENCE public.report_record_seq
    START WITH 1
    INCREMENT BY 50
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER SEQUENCE public.report_record_seq OWNER TO postgres;

--
-- TOC entry 219 (class 1259 OID 16837)
-- Name: semesters; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.semesters (
    id bigint NOT NULL,
    creation_date timestamp(6) with time zone NOT NULL,
    last_modified_date timestamp(6) with time zone,
    active boolean,
    end_date date,
    name character varying(255),
    start_date date,
    order_index integer
);


ALTER TABLE public.semesters OWNER TO postgres;

--
-- TOC entry 226 (class 1259 OID 16877)
-- Name: semesters_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

CREATE SEQUENCE public.semesters_seq
    START WITH 1
    INCREMENT BY 50
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER SEQUENCE public.semesters_seq OWNER TO postgres;

--
-- TOC entry 220 (class 1259 OID 16842)
-- Name: student_class; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.student_class (
    id bigint NOT NULL,
    creation_date timestamp(6) with time zone NOT NULL,
    last_modified_date timestamp(6) with time zone,
    name_student character varying(255),
    student bytea[],
    subject bytea[]
);


ALTER TABLE public.student_class OWNER TO postgres;

--
-- TOC entry 227 (class 1259 OID 16878)
-- Name: student_class_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

CREATE SEQUENCE public.student_class_seq
    START WITH 1
    INCREMENT BY 50
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER SEQUENCE public.student_class_seq OWNER TO postgres;

--
-- TOC entry 239 (class 1259 OID 16956)
-- Name: student_info_requests; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.student_info_requests (
    id bigint NOT NULL,
    creation_date timestamp(6) with time zone NOT NULL,
    last_modified_date timestamp(6) with time zone,
    created_at timestamp(6) without time zone,
    rejection_reason character varying(255),
    requested_changes_json text NOT NULL,
    status character varying(255),
    student_id bigint NOT NULL,
    CONSTRAINT student_info_requests_status_check CHECK (((status)::text = ANY ((ARRAY['PENDING'::character varying, 'APPROVED'::character varying, 'REJECTED'::character varying])::text[])))
);


ALTER TABLE public.student_info_requests OWNER TO postgres;

--
-- TOC entry 240 (class 1259 OID 16964)
-- Name: student_info_requests_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

CREATE SEQUENCE public.student_info_requests_seq
    START WITH 1
    INCREMENT BY 50
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER SEQUENCE public.student_info_requests_seq OWNER TO postgres;

--
-- TOC entry 221 (class 1259 OID 16849)
-- Name: students; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.students (
    id bigint NOT NULL,
    creation_date timestamp(6) with time zone NOT NULL,
    last_modified_date timestamp(6) with time zone,
    email character varying(255),
    first_name character varying(255),
    last_name character varying(255),
    level character varying(255),
    student_number character varying(255),
    cycle character varying(255),
    date_of_birth date,
    place_of_birth character varying(255),
    speciality character varying(255),
    matricule character varying(255)
);


ALTER TABLE public.students OWNER TO postgres;

--
-- TOC entry 228 (class 1259 OID 16879)
-- Name: students_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

CREATE SEQUENCE public.students_seq
    START WITH 1
    INCREMENT BY 50
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER SEQUENCE public.students_seq OWNER TO postgres;

--
-- TOC entry 222 (class 1259 OID 16856)
-- Name: subject; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.subject (
    id bigint NOT NULL,
    creation_date timestamp(6) with time zone NOT NULL,
    last_modified_date timestamp(6) with time zone,
    code character varying(255),
    coefficient numeric(38,2),
    credits numeric(38,2),
    id_teacher bigint,
    name character varying(255),
    active boolean,
    description character varying(500),
    cycle character varying(255),
    level character varying(255),
    id_semester bigint,
    department_id bigint,
    CONSTRAINT subject_cycle_check CHECK (((cycle)::text = ANY ((ARRAY['BACHELOR'::character varying, 'MASTER'::character varying, 'PHD'::character varying])::text[]))),
    CONSTRAINT subject_level_check CHECK (((level)::text = ANY ((ARRAY['LEVEL1'::character varying, 'LEVEL2'::character varying, 'LEVEL3'::character varying, 'LEVEL4'::character varying, 'LEVEL5'::character varying])::text[])))
);


ALTER TABLE public.subject OWNER TO postgres;

--
-- TOC entry 229 (class 1259 OID 16880)
-- Name: subject_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

CREATE SEQUENCE public.subject_seq
    START WITH 1
    INCREMENT BY 50
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER SEQUENCE public.subject_seq OWNER TO postgres;

--
-- TOC entry 223 (class 1259 OID 16863)
-- Name: users; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.users (
    id bigint NOT NULL,
    creation_date timestamp(6) with time zone NOT NULL,
    last_modified_date timestamp(6) with time zone,
    active boolean,
    email character varying(255),
    first_name character varying(255),
    last_name character varying(255),
    password character varying(255),
    phone character varying(30),
    role character varying(255),
    username character varying(255),
    must_change_password boolean,
    department character varying(100),
    CONSTRAINT users_role_check CHECK (((role)::text = ANY ((ARRAY['ADMIN'::character varying, 'STUDENT'::character varying, 'TEACHER'::character varying])::text[])))
);


ALTER TABLE public.users OWNER TO postgres;

--
-- TOC entry 230 (class 1259 OID 16881)
-- Name: users_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

CREATE SEQUENCE public.users_seq
    START WITH 1
    INCREMENT BY 50
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER SEQUENCE public.users_seq OWNER TO postgres;

--
-- TOC entry 3355 (class 2604 OID 17003)
-- Name: grade_claims id; Type: DEFAULT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.grade_claims ALTER COLUMN id SET DEFAULT nextval('public.grade_claims_id_seq'::regclass);


--
-- TOC entry 3583 (class 0 OID 16942)
-- Dependencies: 238
-- Data for Name: departments; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.departments (id, name) FROM stdin;
\.


--
-- TOC entry 3586 (class 0 OID 16975)
-- Dependencies: 241
-- Data for Name: grade_claim; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.grade_claim (id, creation_date, last_modified_date, cause, description, period_label, requested_score, resolved_at, status, teacher_comment, id_grade, id_semester, id_student) FROM stdin;
\.


--
-- TOC entry 3589 (class 0 OID 17000)
-- Dependencies: 244
-- Data for Name: grade_claims; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.grade_claims (id, created_at, rejection_reason, resolved_at, status, cause, description, period_label, requested_score, teacher_comment, created_by_id, grade_id, semester_id, student_id) FROM stdin;
\.


--
-- TOC entry 3562 (class 0 OID 16822)
-- Dependencies: 217
-- Data for Name: grade_report; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.grade_report (id, creation_date, last_modified_date, gpa, id_semesters, id_students, pdf_path, status) FROM stdin;
\.


--
-- TOC entry 3563 (class 0 OID 16829)
-- Dependencies: 218
-- Data for Name: grades; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.grades (id, creation_date, last_modified_date, coefficient, comments, grade_type, value, id_users, id_semester, id_students, id_subject, period_label, max_value) FROM stdin;
1	2025-07-05 00:15:25.958905+01	\N	0.1	poor	ASSIGNMENT	20	203	1	1	1	\N	\N
2	2025-07-05 10:03:56.094901+01	\N	0.1	Poor	ASSIGNMENT	20	203	1	1	1	\N	\N
52	2025-07-05 10:45:24.810561+01	\N	0.1	Do better	EXAM	20	203	1	1	102	\N	\N
102	2025-07-08 15:37:54.638482+01	\N	2	Mid-term	EXAM	14	352	2	2	52	\N	\N
103	2025-07-08 15:49:52.964086+01	\N	5	Mid-term	EXAM	20	352	2	2	302	\N	\N
104	2025-07-08 16:03:16.449387+01	\N	4	Mid-term	EXAM	18	352	2	2	2	\N	\N
105	2025-07-08 16:05:50.808269+01	\N	5	Mid-term	EXAM	18	352	1	2	202	\N	\N
106	2025-07-08 16:07:14.034513+01	\N	5	Mid-term	EXAM	20	352	1	2	252	\N	\N
107	2025-07-08 16:07:58.90752+01	\N	5	Mid-term	EXAM	20	352	1	2	152	\N	\N
108	2025-07-08 16:08:53.419304+01	\N	5	Mid-term	EXAM	5	352	1	2	1	\N	\N
109	2025-07-08 16:09:40.152553+01	\N	5	Mid-term	EXAM	10	352	2	2	102	\N	\N
\.


--
-- TOC entry 3580 (class 0 OID 16930)
-- Dependencies: 235
-- Data for Name: grading_window; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.grading_window (id, creation_date, last_modified_date, active, end_date, name, start_date, id_semester) FROM stdin;
\.


--
-- TOC entry 3579 (class 0 OID 16911)
-- Dependencies: 234
-- Data for Name: invite_token; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.invite_token (id, claimed, expires_at, role, token) FROM stdin;
1	f	2025-07-10 01:00:00+01	TEACHER	be06ccf8c27c418f86b9d3c53f1a5348
2	t	2025-07-11 08:47:30.537+01	ADMIN	7ccf12d67cd345658c7518314a9b335b
3	t	2025-07-10 15:05:23.236+01	TEACHER	c7728b42a3a54679b025946154753925
4	t	2025-07-10 10:40:12.811+01	ADMIN	6aee4756042041618f98fda1fb65620c
5	t	2025-07-10 10:40:12.811+01	TEACHER	c076bce5ba554bd2a52892e40f314d7f
6	t	2025-07-10 10:40:12.811+01	TEACHER	b47664a2fccb45a689cfdd8de0bf5ca4
7	f	2025-07-10 10:40:12.811+01	TEACHER	9d15dd808fd94dbca79b0a7dfe9820bb
8	t	2025-07-10 10:40:12.811+01	TEACHER	37bbcff8810c42a7a3e6d9e3f5834382
9	t	2025-07-10 10:40:12.811+01	TEACHER	83fbc841149c4846acbf5c5a3d1804b0
\.


--
-- TOC entry 3576 (class 0 OID 16902)
-- Dependencies: 231
-- Data for Name: report_record; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.report_record (id, creation_date, last_modified_date, class_id, download_url, generated_by, gpa, pdf_path, report_type, semester_id, status, student_id, subject_id, academic_year, faculty, university_name) FROM stdin;
1	2025-07-05 19:59:43.897955+01	\N	\N	/files/student_1_subject_252_1751741983849.pdf	203	0	generated-reports/student_1_subject_252_1751741983849.pdf	SUBJECT_GRADES	1	FAIL	1	252	\N	\N	\N
2	2025-07-08 16:19:58.526853+01	2025-07-08 16:19:58.418976+01	\N	/files/student_2_sem_2_1751987998411.pdf	352	15.63	generated-reports/student_2_sem_2_1751987998411.pdf	STUDENT_GRADES	2	PASS	2	\N	\N	\N	\N
\.


--
-- TOC entry 3564 (class 0 OID 16837)
-- Dependencies: 219
-- Data for Name: semesters; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.semesters (id, creation_date, last_modified_date, active, end_date, name, start_date, order_index) FROM stdin;
1	2025-07-04 23:06:08.023691+01	\N	t	2026-06-30	2025-2026	2025-09-01	\N
2	2025-07-08 12:57:53.376169+01	\N	t	2028-07-08	2028 - 2029	2026-07-20	\N
52	2025-07-09 11:37:01.401348+01	\N	t	2025-07-20	semester 3	2025-07-10	\N
\.


--
-- TOC entry 3565 (class 0 OID 16842)
-- Dependencies: 220
-- Data for Name: student_class; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.student_class (id, creation_date, last_modified_date, name_student, student, subject) FROM stdin;
\.


--
-- TOC entry 3584 (class 0 OID 16956)
-- Dependencies: 239
-- Data for Name: student_info_requests; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.student_info_requests (id, creation_date, last_modified_date, created_at, rejection_reason, requested_changes_json, status, student_id) FROM stdin;
\.


--
-- TOC entry 3566 (class 0 OID 16849)
-- Dependencies: 221
-- Data for Name: students; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.students (id, creation_date, last_modified_date, email, first_name, last_name, level, student_number, cycle, date_of_birth, place_of_birth, speciality, matricule) FROM stdin;
1	2025-07-05 00:10:13.225413+01	\N	melija@gmail.com	Doknow	melija	\N	35b3e262-0769-44a5-aa90-fd9c19d8d68f	\N	\N	\N	\N	\N
2	2025-07-08 09:04:53.422619+01	\N	arielgrace@gmail.com	Boutchouang	Charis	\N	826f5c1d-d24b-43f6-aaee-0b50c02c5d7c	\N	\N	\N	\N	\N
52	2025-07-09 10:27:35.510635+01	\N	brenda@gmail.com	Nathou	Boutchouang	\N	d41a4a1b-8b70-44ca-8e2a-8e18ea553ab1	\N	\N	\N	\N	\N
53	2025-07-09 11:12:36.556482+01	\N	derrick@gmail	Blue	Derrick	\N	97a620dd-02e4-4ad1-9de5-3307eed9045d	\N	\N	\N	\N	\N
102	2025-07-20 15:14:04.619761+01	\N	student1@example.com	Student1	Level1	LEVEL1	\N	BACHELOR	\N	\N	\N	MAT4BE3B9
103	2025-07-20 15:14:04.746432+01	\N	student2@example.com	Student2	Level2	LEVEL2	\N	BACHELOR	\N	\N	\N	MAT70ED5E
104	2025-07-20 15:14:04.907995+01	\N	student3@example.com	Student3	Level3	LEVEL3	\N	BACHELOR	\N	\N	\N	MATA15FFB
105	2025-07-20 15:14:05.045283+01	\N	student4@example.com	Student4	Level4	LEVEL4	\N	MASTER	\N	\N	\N	MAT6D223A
106	2025-07-20 15:14:05.225761+01	\N	student5@example.com	Student5	Level5	LEVEL5	\N	MASTER	\N	\N	\N	MAT8F84BB
152	2025-07-20 15:18:04.523365+01	\N	student@example.com	Default	Student	LEVEL1	\N	BACHELOR	\N	\N	\N	MAT64271B
202	2025-08-21 15:15:47.745043+01	\N	playerDgjg@gmail.com	Noname	surprise	LEVEL1	\N	BACHELOR	\N	\N	\N	20s2128
252	2025-08-21 15:51:06.810501+01	\N	john.smith@example.com	John	Smith	LEVEL1	\N	BACHELOR	\N	\N	\N	20B00123
253	2025-08-21 15:52:31.196681+01	\N	joleisnh@example.com	sisdf	lsknnee	\N	\N	\N	\N	\N	\N	08f34160-b1cc-4f5d-a738-1cd5e4f72eae
302	2025-08-22 12:41:55.855251+01	\N	sample.student@university.com	Sample	Student	\N	\N	\N	\N	\N	\N	\N
\.


--
-- TOC entry 3567 (class 0 OID 16856)
-- Dependencies: 222
-- Data for Name: subject; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.subject (id, creation_date, last_modified_date, code, coefficient, credits, id_teacher, name, active, description, cycle, level, id_semester, department_id) FROM stdin;
1	2025-07-04 22:29:35.747802+01	\N	1024	0.10	5.00	203	Math	\N	\N	\N	\N	\N	\N
2	2025-07-04 22:41:50.168452+01	\N	604	0.10	4.00	203	chemistry	\N	\N	\N	\N	\N	\N
52	2025-07-05 10:18:11.103639+01	\N	2024	0.70	3.00	203	Biology	\N	\N	\N	\N	\N	\N
102	2025-07-05 10:42:25.658174+01	\N	203	0.40	1.00	203	Religious Studies	\N	\N	\N	\N	\N	\N
152	2025-07-05 18:28:47.729287+01	\N	1082	2.00	4.00	203	Geography	\N	\N	\N	\N	\N	\N
202	2025-07-05 19:46:41.630392+01	\N	404	0.10	1.00	203	coding	\N	\N	\N	\N	\N	\N
252	2025-07-05 19:58:25.686085+01	\N	300	0.10	1.00	203	commerce	\N	\N	\N	\N	\N	\N
302	2025-07-08 14:05:00.473238+01	\N	BCH3021	0.10	1.00	203	Biochemistry	t	Biochemistry of life	\N	\N	\N	\N
352	2025-07-09 14:50:15.106034+01	\N	BAN2939	\N	5.00	\N	Cody	t	You need to code for real	\N	\N	\N	\N
\.


--
-- TOC entry 3568 (class 0 OID 16863)
-- Dependencies: 223
-- Data for Name: users; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.users (id, creation_date, last_modified_date, active, email, first_name, last_name, password, phone, role, username, must_change_password, department) FROM stdin;
1	2025-07-02 15:16:54.425855+01	\N	\N	admin@example.com	\N	\N	$2a$10$ErTNxy3dlRmKIYUyrbLttucRZI4jEHwPxK4ZiRRTFc.Y/tIHTUYQO	\N	ADMIN	admin	\N	\N
3	2025-07-03 14:30:01.220922+01	\N	t	marieclara@gmail.com	Marieclara	croquette	$2a$10$O3a8Ia/moRv9m/nWEP7LD.rEJWZvnc5sMasfIZe8oY5DhBfLrXheS	+6613487722	\N	Marie	\N	\N
4	2025-07-03 14:31:54.04757+01	\N	t	duchelle@gmail.com	Mboutch	Duchelle	$2a$10$piBvD4Y7lEK8vThVsT0auegy95teCtl2Yocrs0tWQCv59amWfmv8W	+6613487722	\N	Stella	\N	\N
52	2025-07-03 20:17:41.561083+01	\N	t	mboutch@gmail.com	Duchelle	stella	$2a$10$cehqcZ3dlUgsIyE59a0OFuiijzu3pFvDlIELP8hVOliwutPVWdwom	+1064673630	\N	mboutch	\N	\N
102	2025-07-03 20:36:07.66158+01	\N	t	jeremy@gmail.com	Djambon	Enora	$2a$10$dn/HvRy/mJo2Z1AVFqXBN.VtCdJIXZDxLsPTFKAxMAKqNEdVpabyy	+59329609909	ADMIN	bright	\N	\N
103	2025-07-03 20:50:29.185942+01	\N	t	nathanelija@gmail.com	Boutchouang	Nathan	$2a$10$nTEGOxjd5t.fOUR3vkoNa.Td4Sg1MKNjJu8HYODFcB0MBWGBpQpgm	+59329609909	STUDENT	nathan	\N	\N
152	2025-07-03 21:24:43.660317+01	\N	t	asopdongD@gmail.com	Asopdong	deovie	$2a$10$LzLZg4kpNER2g62falpfVucQ.Y8HeaSf6QN4Bf3wZ6iwDLUjiCG1e	+55292250843073	STUDENT	deovie	\N	\N
202	2025-07-04 16:10:28.937999+01	\N	t	charis@gmail.com	Boutchouang	Elija	$2a$10$y4Mg/P2/k0oaCXSy3cHbb.eUR8JQaFaph6PE.yc1sBEXkZ0Csmbre	396271233261	STUDENT	charis	\N	\N
203	2025-07-04 16:43:19.123928+01	\N	t	alice@school.edu	Alice	Smith	$2a$10$kNY8j7cKOpanDxSK8cyBY.ynEYHzcwrNrUfRlk82ChUpzhnHCwSRS	396271233261	TEACHER	teacher1	\N	\N
252	2025-07-05 00:10:13.085045+01	\N	t	melija@gmail.com	Doknow	melija	$2a$10$9RDjaKZIbCpsUMM4juCiaeBmKNd0Y5RPbM49bwosHIN1kXUEY89Oi	+386354967253	STUDENT	melisa	\N	\N
302	2025-07-08 08:57:08.04346+01	\N	t	noname@gmail.com	ralpn	king	$2a$10$t/rb5jdhGrw/6/ExzbOHauL7EFH4QSieyOxeu6C3aHMLf4ObuwiWq	+237641235687	ADMIN	duchellel	\N	\N
303	2025-07-08 09:04:53.399129+01	\N	t	arielgrace@gmail.com	Boutchouang	Charis	$2a$10$H6WEAVDp2lRdhyJ9vvOcwuwn/kDTEExP2xJGnNTM/N9y1amAmMeoG	+237641232087	STUDENT	charisa	\N	\N
352	2025-07-08 15:07:20.433865+01	\N	t	escanor@gmail.com	Escanor	Stratis	$2a$10$04srFcRqG81Kbee.DPyC/OnuViqufORiC6bQzBHA4Z5k4FFFmyR8.	+526544841700	TEACHER	Escanor	\N	\N
402	2025-07-09 10:27:35.404339+01	\N	t	brenda@gmail.com	Nathou	Boutchouang	$2a$10$PO9ElYpgfMQcIcxckhoJRu9/BZyStCy6HhtnW./H/EltP6wJ6k4oW	+237670710914	STUDENT	brenda	\N	\N
403	2025-07-09 10:52:27.72077+01	\N	t	marie@gmail	Blue	Marie	$2a$10$mp1bVF/VgBa7rt9uMEHfWe9YpqLVebKbY52tAB1U4WIgkSWm6v0b2	715791005707	ADMIN	mary	\N	\N
404	2025-07-09 10:56:33.237312+01	\N	t	divine@gmail	Blue	Divine	$2a$10$jpUq74tDypBNfhWxRXUTJOJAf/1vIxqXTlL1LSCJDQtMcztbI36Iy	715791005707	TEACHER	divine	\N	\N
405	2025-07-09 10:59:40.972375+01	\N	t	nathou@gmail	Blue	Nathou	$2a$10$clFZLu6sN8jNcH8BL5MWL.C4mwamr6F.FHah.n2Ag2pIj932ZZcpS	715791005707	TEACHER	nathou	\N	\N
406	2025-07-09 11:10:37.31806+01	\N	t	minou@gmail	Blue	Minou	$2a$10$UX3llc7WdNOQoQDbwY8doeS8.FKxHGQLnupLt1h5Vms/OPlrjFfE.	715791005707	TEACHER	minou	\N	\N
407	2025-07-09 11:12:36.540521+01	\N	t	derrick@gmail	Blue	Derrick	$2a$10$2T0WvJqWRUpB6d9ZIavbQeXy9jY4kqD/qYVACbhrduzmdLTMZoYPe	715791005707	STUDENT	derrick	\N	\N
408	2025-07-09 11:16:49.664555+01	\N	t	richard@gmail	Blue	Richard	$2a$10$jbrb8RBjZS0C7w6yZEZHaeuyB53oSRpFkHhmtWYvSsY0evBbbDCM2	715791005707	TEACHER	richard	\N	\N
452	2025-07-20 15:14:04.510653+01	\N	t	student1@example.com	Student1	Level1	$2a$10$n5gxIT34PR6kk018LfdE/u.PiBWFS65C6v0AdHHMnt9Km7dWvdDym	\N	STUDENT	student1	\N	\N
453	2025-07-20 15:14:04.742203+01	\N	t	student2@example.com	Student2	Level2	$2a$10$phhoWIUbZP1zOuCDzt7iReEE1gfgJB5LyyPXExq7dVpzuSCD3I9xy	\N	STUDENT	student2	\N	\N
454	2025-07-20 15:14:04.888734+01	\N	t	student3@example.com	Student3	Level3	$2a$10$ONShBDcpfNBJrP2KB8QoKuM7vI4js2oyH450.9ygJGJOIXAvGhCYu	\N	STUDENT	student3	\N	\N
455	2025-07-20 15:14:05.040219+01	\N	t	student4@example.com	Student4	Level4	$2a$10$BaeZ14IipSDiF2CgweASH.LgvBTJUZQHyBBQeJwjD1L8iZWdL.kn6	\N	STUDENT	student4	\N	\N
456	2025-07-20 15:14:05.205382+01	\N	t	student5@example.com	Student5	Level5	$2a$10$hzlNbqRWWUBkvPNRPqFqAeFkZxAqDPd/dWO1tD0U23IPOQGWPKrAu	\N	STUDENT	student5	\N	\N
502	2025-07-20 15:18:04.411473+01	\N	t	student@example.com	Default	Student	$2a$10$Q0I0cPJOumzC/ZIn.XGqmONTWPBxXSdU701s3Q7xDrtEFNtDOeNgS	\N	STUDENT	student	\N	\N
503	2025-07-20 15:18:04.725422+01	\N	t	teacher@example.com	Default	Teacher	$2a$10$lTXTiWiiuOubkM6zfGkr..kQIotoFJwtwepm393.Jh.u/bBxgfaam	\N	TEACHER	teacher	\N	\N
2	2025-07-03 14:28:28.779894+01	\N	t	boutchouangelija@gmail.com	Boutchouang	Elija	$2a$10$I5MB.L8tWkcckD8FwqDLh.acxEJgnfRJx1/YuWc2PWe67Y6tu8jpG	+6613409722	\N	Nathan	\N	\N
552	2025-08-21 15:15:47.673138+01	\N	t	playerDgjg@gmail.com	Noname	surprise	$2a$10$I0NB6efg3tBzo7Kf0n9QdORH6S.yywR6AvDm3XAeW7RlQXUMxx1xq	\N	STUDENT	20s2128	t	\N
602	2025-08-21 15:51:06.715997+01	\N	t	john.smith@example.com	John	Smith	$2a$10$GRI45EDBecXX/BvWYscFsO/90rbmY2vcph7Eub7wKqeDGRJqJArqi	\N	STUDENT	20B00123	t	\N
603	2025-08-21 15:52:31.185615+01	\N	t	joleisnh@example.com	sisdf	lsknnee	$2a$10$LLRSu0TSN5YJ5HzHq2LGk.9K64xJWcQFyIcP1O/n/hHgvkx5IqK6e	\N	STUDENT	08f34160-b1cc-4f5d-a738-1cd5e4f72eae	t	\N
604	2025-08-21 15:53:51.317618+01	\N	t	jreksiisnh@example.com	lusci	ninin	$2a$10$fLO8r2.JcgyjGi99EwI/wew8pjYC3595OC54pk6q2QU4onNa88Iqm	\N	TEACHER	sabddudr	t	\N
\.


--
-- TOC entry 3596 (class 0 OID 0)
-- Dependencies: 237
-- Name: departments_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.departments_id_seq', 1, false);


--
-- TOC entry 3597 (class 0 OID 0)
-- Dependencies: 242
-- Name: grade_claim_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.grade_claim_seq', 1, false);


--
-- TOC entry 3598 (class 0 OID 0)
-- Dependencies: 243
-- Name: grade_claims_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.grade_claims_id_seq', 1, false);


--
-- TOC entry 3599 (class 0 OID 0)
-- Dependencies: 224
-- Name: grade_report_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.grade_report_seq', 1, false);


--
-- TOC entry 3600 (class 0 OID 0)
-- Dependencies: 225
-- Name: grades_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.grades_seq', 201, true);


--
-- TOC entry 3601 (class 0 OID 0)
-- Dependencies: 236
-- Name: grading_window_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.grading_window_seq', 1, false);


--
-- TOC entry 3602 (class 0 OID 0)
-- Dependencies: 233
-- Name: invite_token_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.invite_token_id_seq', 9, true);


--
-- TOC entry 3603 (class 0 OID 0)
-- Dependencies: 232
-- Name: report_record_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.report_record_seq', 51, true);


--
-- TOC entry 3604 (class 0 OID 0)
-- Dependencies: 226
-- Name: semesters_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.semesters_seq', 101, true);


--
-- TOC entry 3605 (class 0 OID 0)
-- Dependencies: 227
-- Name: student_class_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.student_class_seq', 1, false);


--
-- TOC entry 3606 (class 0 OID 0)
-- Dependencies: 240
-- Name: student_info_requests_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.student_info_requests_seq', 1, false);


--
-- TOC entry 3607 (class 0 OID 0)
-- Dependencies: 228
-- Name: students_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.students_seq', 351, true);


--
-- TOC entry 3608 (class 0 OID 0)
-- Dependencies: 229
-- Name: subject_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.subject_seq', 401, true);


--
-- TOC entry 3609 (class 0 OID 0)
-- Dependencies: 230
-- Name: users_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.users_seq', 651, true);


--
-- TOC entry 3393 (class 2606 OID 16946)
-- Name: departments departments_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.departments
    ADD CONSTRAINT departments_pkey PRIMARY KEY (id);


--
-- TOC entry 3399 (class 2606 OID 16982)
-- Name: grade_claim grade_claim_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.grade_claim
    ADD CONSTRAINT grade_claim_pkey PRIMARY KEY (id);


--
-- TOC entry 3401 (class 2606 OID 17008)
-- Name: grade_claims grade_claims_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.grade_claims
    ADD CONSTRAINT grade_claims_pkey PRIMARY KEY (id);


--
-- TOC entry 3365 (class 2606 OID 16828)
-- Name: grade_report grade_report_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.grade_report
    ADD CONSTRAINT grade_report_pkey PRIMARY KEY (id);


--
-- TOC entry 3367 (class 2606 OID 16836)
-- Name: grades grades_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.grades
    ADD CONSTRAINT grades_pkey PRIMARY KEY (id);


--
-- TOC entry 3391 (class 2606 OID 16934)
-- Name: grading_window grading_window_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.grading_window
    ADD CONSTRAINT grading_window_pkey PRIMARY KEY (id);


--
-- TOC entry 3387 (class 2606 OID 16918)
-- Name: invite_token invite_token_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.invite_token
    ADD CONSTRAINT invite_token_pkey PRIMARY KEY (id);


--
-- TOC entry 3385 (class 2606 OID 16908)
-- Name: report_record report_record_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.report_record
    ADD CONSTRAINT report_record_pkey PRIMARY KEY (id);


--
-- TOC entry 3369 (class 2606 OID 16841)
-- Name: semesters semesters_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.semesters
    ADD CONSTRAINT semesters_pkey PRIMARY KEY (id);


--
-- TOC entry 3371 (class 2606 OID 16848)
-- Name: student_class student_class_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.student_class
    ADD CONSTRAINT student_class_pkey PRIMARY KEY (id);


--
-- TOC entry 3397 (class 2606 OID 16963)
-- Name: student_info_requests student_info_requests_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.student_info_requests
    ADD CONSTRAINT student_info_requests_pkey PRIMARY KEY (id);


--
-- TOC entry 3373 (class 2606 OID 16855)
-- Name: students students_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.students
    ADD CONSTRAINT students_pkey PRIMARY KEY (id);


--
-- TOC entry 3379 (class 2606 OID 16862)
-- Name: subject subject_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.subject
    ADD CONSTRAINT subject_pkey PRIMARY KEY (id);


--
-- TOC entry 3375 (class 2606 OID 16922)
-- Name: students uk1psraxut9bwn2why6ex4xf1en; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.students
    ADD CONSTRAINT uk1psraxut9bwn2why6ex4xf1en UNIQUE (matricule);


--
-- TOC entry 3389 (class 2606 OID 16920)
-- Name: invite_token uk60k2cybcnd18p0cnf0e5sssb6; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.invite_token
    ADD CONSTRAINT uk60k2cybcnd18p0cnf0e5sssb6 UNIQUE (token);


--
-- TOC entry 3377 (class 2606 OID 16872)
-- Name: students ukh7gboo6v79gig1eo7lt1fubew; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.students
    ADD CONSTRAINT ukh7gboo6v79gig1eo7lt1fubew UNIQUE (student_number);


--
-- TOC entry 3395 (class 2606 OID 16948)
-- Name: departments ukj6cwks7xecs5jov19ro8ge3qk; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.departments
    ADD CONSTRAINT ukj6cwks7xecs5jov19ro8ge3qk UNIQUE (name);


--
-- TOC entry 3381 (class 2606 OID 16874)
-- Name: users ukr43af9ap4edm43mmtq01oddj6; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.users
    ADD CONSTRAINT ukr43af9ap4edm43mmtq01oddj6 UNIQUE (username);


--
-- TOC entry 3383 (class 2606 OID 16870)
-- Name: users users_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.users
    ADD CONSTRAINT users_pkey PRIMARY KEY (id);


--
-- TOC entry 3413 (class 2606 OID 17014)
-- Name: grade_claims fk2kbul9dstw4uo15gc5tomfkni; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.grade_claims
    ADD CONSTRAINT fk2kbul9dstw4uo15gc5tomfkni FOREIGN KEY (grade_id) REFERENCES public.grades(id);


--
-- TOC entry 3402 (class 2606 OID 16892)
-- Name: grades fk384e8h2qimc9qlnh970ytgdr5; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.grades
    ADD CONSTRAINT fk384e8h2qimc9qlnh970ytgdr5 FOREIGN KEY (id_students) REFERENCES public.students(id);


--
-- TOC entry 3406 (class 2606 OID 16925)
-- Name: subject fk4b66tj7yip7jmo922vvy6bw4y; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.subject
    ADD CONSTRAINT fk4b66tj7yip7jmo922vvy6bw4y FOREIGN KEY (id_semester) REFERENCES public.semesters(id);


--
-- TOC entry 3410 (class 2606 OID 16984)
-- Name: grade_claim fk89upq1hqsa0g35ml01y3ss7e3; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.grade_claim
    ADD CONSTRAINT fk89upq1hqsa0g35ml01y3ss7e3 FOREIGN KEY (id_grade) REFERENCES public.grades(id);


--
-- TOC entry 3414 (class 2606 OID 17009)
-- Name: grade_claims fk8b4k9pw7j018vpks0ns5wmsp0; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.grade_claims
    ADD CONSTRAINT fk8b4k9pw7j018vpks0ns5wmsp0 FOREIGN KEY (created_by_id) REFERENCES public.users(id);


--
-- TOC entry 3411 (class 2606 OID 16994)
-- Name: grade_claim fk9x40h9g78vq6p16ifrskjcmfl; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.grade_claim
    ADD CONSTRAINT fk9x40h9g78vq6p16ifrskjcmfl FOREIGN KEY (id_student) REFERENCES public.students(id);


--
-- TOC entry 3412 (class 2606 OID 16989)
-- Name: grade_claim fkanjtrx9f1rrxr0dmjfwl0oksb; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.grade_claim
    ADD CONSTRAINT fkanjtrx9f1rrxr0dmjfwl0oksb FOREIGN KEY (id_semester) REFERENCES public.semesters(id);


--
-- TOC entry 3415 (class 2606 OID 17024)
-- Name: grade_claims fkc1rbjpi3wpf5ihn0h81pygtnc; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.grade_claims
    ADD CONSTRAINT fkc1rbjpi3wpf5ihn0h81pygtnc FOREIGN KEY (student_id) REFERENCES public.students(id);


--
-- TOC entry 3409 (class 2606 OID 16965)
-- Name: student_info_requests fkfawh6psw2f3yivjbpciph35nh; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.student_info_requests
    ADD CONSTRAINT fkfawh6psw2f3yivjbpciph35nh FOREIGN KEY (student_id) REFERENCES public.students(id);


--
-- TOC entry 3403 (class 2606 OID 16882)
-- Name: grades fkfrqv6jj26ycmq0uqihsmofd9w; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.grades
    ADD CONSTRAINT fkfrqv6jj26ycmq0uqihsmofd9w FOREIGN KEY (id_users) REFERENCES public.users(id);


--
-- TOC entry 3404 (class 2606 OID 16897)
-- Name: grades fkippbjcacm6nkn7hon47r53l99; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.grades
    ADD CONSTRAINT fkippbjcacm6nkn7hon47r53l99 FOREIGN KEY (id_subject) REFERENCES public.subject(id);


--
-- TOC entry 3408 (class 2606 OID 16936)
-- Name: grading_window fkmkan866y61akk4qim8e74d3dj; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.grading_window
    ADD CONSTRAINT fkmkan866y61akk4qim8e74d3dj FOREIGN KEY (id_semester) REFERENCES public.semesters(id);


--
-- TOC entry 3407 (class 2606 OID 16970)
-- Name: subject fkqym877gemkcwuhmjmbuokvf6f; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.subject
    ADD CONSTRAINT fkqym877gemkcwuhmjmbuokvf6f FOREIGN KEY (department_id) REFERENCES public.departments(id);


--
-- TOC entry 3405 (class 2606 OID 16887)
-- Name: grades fks0yeww9160sohy3wpgmt7dve; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.grades
    ADD CONSTRAINT fks0yeww9160sohy3wpgmt7dve FOREIGN KEY (id_semester) REFERENCES public.semesters(id);


--
-- TOC entry 3416 (class 2606 OID 17019)
-- Name: grade_claims fkteaqiirgxcnndhnx4ljcoc60h; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.grade_claims
    ADD CONSTRAINT fkteaqiirgxcnndhnx4ljcoc60h FOREIGN KEY (semester_id) REFERENCES public.semesters(id);


-- Completed on 2025-08-22 14:18:43 WAT

--
-- PostgreSQL database dump complete
--

